/** @file

  Renesas USB Controller

  SPDX-FileCopyrightText: Copyright (c) 2023-2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#ifndef __RENESAS_USB_CTLR_H__
#define __RENESAS_USB_CTLR_H__

#define PCI_VENDOR_ID_RENESAS  0x1912

#define PCI_DEVICE_ID_UPD720201  0x0014
#define PCI_DEVICE_ID_UPD720202  0x0015

#define PCI_RENESAS_FW_DL_CTL_STS_REG    0xF4
#define PCI_RENESAS_EXT_ROM_CTL_STS_REG  0xF6
#define PCI_RENESAS_DATA0_REG            0xF8
#define PCI_RENESAS_DATA1_REG            0xFC

#define FW_DL_CTL_STS_DOWNLOAD_ENABLE_BIT  0
#define FW_DL_CTL_STS_DOWNLOAD_LOCK_BIT    1
#define FW_DL_CTL_STS_RESULT_CODE_LSB      4
#define FW_DL_CTL_STS_RESULT_CODE_MSB      6
#define FW_DL_CTL_STS_SET_DATA0_BIT        8
#define FW_DL_CTL_STS_SET_DATA1_BIT        9

#define EXT_ROM_CTL_STS_EXT_ROM_EXISTS_BIT  15

#define FW_DL_CTL_STS_DOWNLOAD_ENABLE_MSK  (1 << FW_DL_CTL_STS_DOWNLOAD_ENABLE_BIT)
#define FW_DL_CTL_STS_DOWNLOAD_LOCK_MSK    (1 << FW_DL_CTL_STS_DOWNLOAD_LOCK_BIT  )
#define FW_DL_CTL_STS_SET_DATA0_MSK        (1 << FW_DL_CTL_STS_SET_DATA0_BIT      )
#define FW_DL_CTL_STS_SET_DATA1_MSK        (1 << FW_DL_CTL_STS_SET_DATA1_BIT      )

#define FW_DL_CTL_STS_RESULT_CODE_SUCCESS_SET_MSK    0x0010
#define FW_DL_CTL_STS_RESULT_CODE_SUCCESS_CLEAR_MSK  0x0060

#define EXT_ROM_CTL_STS_EXT_ROM_EXISTS_MSK  (1 << EXT_ROM_CTL_STS_EXT_ROM_EXISTS_BIT)

#define FW_DL_TIMEOUT_US  100000

#endif
