/** @file
 *  Nvidia Configuration Dxe
 *
 *  SPDX-FileCopyrightText: Copyright (c) 2020-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 *  Copyright (c) 2017, Linaro Limited. All rights reserved.
 *
 *  SPDX-License-Identifier: BSD-2-Clause-Patent
 *
 **/

#ifndef __NVIDIA_CONFIG_HII_H__
#define __NVIDIA_CONFIG_HII_H__

#include <Guid/NVIDIAPublicVariableGuid.h>
#include <Guid/NVIDIATokenSpaceGuid.h>
#include <NVIDIAConfiguration.h>

#define NVIDIA_CONFIG_FORMSET_GUID                                                 \
  {                                                                                \
    0x685c0b6e, 0x11af, 0x47cf, { 0xa9, 0xef, 0x95, 0xac, 0x18, 0x68, 0x73, 0xc3 } \
  }

#define NVIDIA_CONFIG_FORM_ID                      0x0001
#define PCIE_CONFIGURATION_FORM_ID                 0x0002
#define BOOT_CONFIGURATION_FORM_ID                 0x0003
#define L4T_CONFIGURATION_FORM_ID                  0x0004
#define TH500_CONFIGURATION_FORM_ID                0x0005
#define TH500_SOCKET0_CONFIGURATION_FORM_ID        0x0006
#define TH500_SOCKET1_CONFIGURATION_FORM_ID        0x0007
#define TH500_SOCKET2_CONFIGURATION_FORM_ID        0x0008
#define TH500_SOCKET3_CONFIGURATION_FORM_ID        0x0009
#define TH500_SOCKET0_PCIE0_CONFIGURATION_FORM_ID  0x000A
#define TH500_SOCKET0_PCIE1_CONFIGURATION_FORM_ID  0x000B
#define TH500_SOCKET0_PCIE2_CONFIGURATION_FORM_ID  0x000C
#define TH500_SOCKET0_PCIE3_CONFIGURATION_FORM_ID  0x000D
#define TH500_SOCKET0_PCIE4_CONFIGURATION_FORM_ID  0x000E
#define TH500_SOCKET0_PCIE5_CONFIGURATION_FORM_ID  0x000F
#define TH500_SOCKET0_PCIE6_CONFIGURATION_FORM_ID  0x0010
#define TH500_SOCKET0_PCIE7_CONFIGURATION_FORM_ID  0x0011
#define TH500_SOCKET0_PCIE8_CONFIGURATION_FORM_ID  0x0012
#define TH500_SOCKET0_PCIE9_CONFIGURATION_FORM_ID  0x0013
#define TH500_SOCKET1_PCIE0_CONFIGURATION_FORM_ID  0x0014
#define TH500_SOCKET1_PCIE1_CONFIGURATION_FORM_ID  0x0015
#define TH500_SOCKET1_PCIE2_CONFIGURATION_FORM_ID  0x0016
#define TH500_SOCKET1_PCIE3_CONFIGURATION_FORM_ID  0x0017
#define TH500_SOCKET1_PCIE4_CONFIGURATION_FORM_ID  0x0018
#define TH500_SOCKET1_PCIE5_CONFIGURATION_FORM_ID  0x0019
#define TH500_SOCKET1_PCIE6_CONFIGURATION_FORM_ID  0x001A
#define TH500_SOCKET1_PCIE7_CONFIGURATION_FORM_ID  0x001B
#define TH500_SOCKET1_PCIE8_CONFIGURATION_FORM_ID  0x001C
#define TH500_SOCKET1_PCIE9_CONFIGURATION_FORM_ID  0x001D
#define TH500_SOCKET2_PCIE0_CONFIGURATION_FORM_ID  0x001E
#define TH500_SOCKET2_PCIE1_CONFIGURATION_FORM_ID  0x001F
#define TH500_SOCKET2_PCIE2_CONFIGURATION_FORM_ID  0x0020
#define TH500_SOCKET2_PCIE3_CONFIGURATION_FORM_ID  0x0021
#define TH500_SOCKET2_PCIE4_CONFIGURATION_FORM_ID  0x0022
#define TH500_SOCKET2_PCIE5_CONFIGURATION_FORM_ID  0x0023
#define TH500_SOCKET2_PCIE6_CONFIGURATION_FORM_ID  0x0024
#define TH500_SOCKET2_PCIE7_CONFIGURATION_FORM_ID  0x0025
#define TH500_SOCKET2_PCIE8_CONFIGURATION_FORM_ID  0x0026
#define TH500_SOCKET2_PCIE9_CONFIGURATION_FORM_ID  0x0027
#define TH500_SOCKET3_PCIE0_CONFIGURATION_FORM_ID  0x0028
#define TH500_SOCKET3_PCIE1_CONFIGURATION_FORM_ID  0x0029
#define TH500_SOCKET3_PCIE2_CONFIGURATION_FORM_ID  0x002A
#define TH500_SOCKET3_PCIE3_CONFIGURATION_FORM_ID  0x002B
#define TH500_SOCKET3_PCIE4_CONFIGURATION_FORM_ID  0x002C
#define TH500_SOCKET3_PCIE5_CONFIGURATION_FORM_ID  0x002D
#define TH500_SOCKET3_PCIE6_CONFIGURATION_FORM_ID  0x002E
#define TH500_SOCKET3_PCIE7_CONFIGURATION_FORM_ID  0x002F
#define TH500_SOCKET3_PCIE8_CONFIGURATION_FORM_ID  0x0030
#define TH500_SOCKET3_PCIE9_CONFIGURATION_FORM_ID  0x0031
#define DEBUG_CONFIGURATION_FORM_ID                0x0032
#define NVIDIA_PRODUCT_INFO_FORM_ID                0x0033
#define MEMORY_TEST_FORM_ID                        0x0034
#define TH500_MPAM_CONFIGURATION_FORM_ID           0x0035
#define TH500_MPAM40_CONFIGURATION_FORM_ID         0x0036
#define TH500_MPAM41_CONFIGURATION_FORM_ID         0x0037
#define TH500_MPAM42_CONFIGURATION_FORM_ID         0x0038
#define TH500_MPAM43_CONFIGURATION_FORM_ID         0x0039
#define TH500_MPAM44_CONFIGURATION_FORM_ID         0x003A

#define KEY_ENABLE_PCIE_CONFIG          0x1000
#define KEY_ENABLE_PCIE_IN_OS_CONFIG    0x1001
#define KEY_ENABLE_QUICK_BOOT           0x1002
#define KEY_NEW_DEVICE_HIERARCHY        0x1003
#define KEY_SERIAL_PORT_CONFIG          0x1004
#define KEY_KERNEL_CMDLINE              0x1005
#define KEY_L4T_BOOTMODE_DEFAULT        0x1006
#define KEY_RESET_VARIABLES             0x1007
#define KEY_OS_CHAIN_STATUS_A           0x1008
#define KEY_OS_CHAIN_STATUS_B           0x1009
#define KEY_L4T_CONFIG                  0x100A
#define KEY_BOOT_CONFIG                 0x100B
#define KEY_IPMI_NETWORK_BOOT_MODE      0x100C
#define KEY_ENABLE_ACPI_TIMER           0x100D
#define KEY_DGPU_DT_EFIFB_SUPPORT       0x100E
#define KEY_ENABLE_HOST_INTERFACE       0x100F
#define KEY_PRODUCT_INFO                0x1010
#define KEY_PRODUCT_CHASSIS_ASSET_TAG   0x1011
#define KEY_ENABLE_UEFI_SHELL           0x1012
#define KEY_ASSET_TAG_PROTECTION        0x1013
#define KEY_GRACE_CONFIG                0x1014
#define KEY_DEBUG_CONFIG                0x1015
#define KEY_ENABLE_TPM                  0x1016
#define KEY_MEMORY_TEST                 0x1017
#define KEY_MEMORY_TEST_LEVEL           0x1018
#define KEY_SOC_DISPLAY_HANDOFF_MODE    0x1019
#define KEY_ENABLE_EGM                  0x101A
#define KEY_EGM_HV_SIZE_MB              0x101B
#define KEY_SPREAD_SPECTRUM             0x101C
#define KEY_MODS_SP_ENABLE              0x101D
#define KEY_GPU_SMMU_BYPASS_ENABLE      0x101E
#define KEY_UART_BAUD_RATE              0x101F
#define KEY_PERF_VERSION                0x1020
#define KEY_UEFI_DEBUG_LEVEL            0x1021
#define KEY_EINJ_ENABLE                 0x1022
#define KEY_MAX_CORES                   0x1023
#define KEY_SERVER_POWER_CONTROL        0x1024
#define KEY_DBG2_NETWORK_DEVICE         0x1025
#define KEY_DISABLE_CHANNEL_SPARING     0x1026
#define KEY_EGM_HV_MIN_EGM_SIZE_MB      0x1027
#define KEY_EGM_HV_VIRT_UEFI_SIZE_MB    0x1028
#define KEY_ECC_ALGORITHM               0x1029
#define KEY_MAX_ALLOWED_NUM_SPARES      0x102A
#define KEY_SOC_DISPLAY_HANDOFF_METHOD  0x102B

#define KEY_UPHY0_SOCKET0_CONFIG  0x1100
#define KEY_UPHY1_SOCKET0_CONFIG  0x1101
#define KEY_UPHY2_SOCKET0_CONFIG  0x1102
#define KEY_UPHY3_SOCKET0_CONFIG  0x1103
#define KEY_UPHY4_SOCKET0_CONFIG  0x1104
#define KEY_UPHY5_SOCKET0_CONFIG  0x1105
#define KEY_UPHY0_SOCKET1_CONFIG  0x1106
#define KEY_UPHY1_SOCKET1_CONFIG  0x1107
#define KEY_UPHY2_SOCKET1_CONFIG  0x1108
#define KEY_UPHY3_SOCKET1_CONFIG  0x1109
#define KEY_UPHY4_SOCKET1_CONFIG  0x110A
#define KEY_UPHY5_SOCKET1_CONFIG  0x110B
#define KEY_UPHY0_SOCKET2_CONFIG  0x110C
#define KEY_UPHY1_SOCKET2_CONFIG  0x110D
#define KEY_UPHY2_SOCKET2_CONFIG  0x110E
#define KEY_UPHY3_SOCKET2_CONFIG  0x110F
#define KEY_UPHY4_SOCKET2_CONFIG  0x1110
#define KEY_UPHY5_SOCKET2_CONFIG  0x1111
#define KEY_UPHY0_SOCKET3_CONFIG  0x1112
#define KEY_UPHY1_SOCKET3_CONFIG  0x1113
#define KEY_UPHY2_SOCKET3_CONFIG  0x1114
#define KEY_UPHY3_SOCKET3_CONFIG  0x1115
#define KEY_UPHY4_SOCKET3_CONFIG  0x1116
#define KEY_UPHY5_SOCKET3_CONFIG  0x1117

#define KEY_SOCKET0_PCIE0_MAX_SPEED  0x1201
#define KEY_SOCKET0_PCIE1_MAX_SPEED  0x1202
#define KEY_SOCKET0_PCIE2_MAX_SPEED  0x1203
#define KEY_SOCKET0_PCIE3_MAX_SPEED  0x1204
#define KEY_SOCKET0_PCIE4_MAX_SPEED  0x1205
#define KEY_SOCKET0_PCIE5_MAX_SPEED  0x1206
#define KEY_SOCKET0_PCIE6_MAX_SPEED  0x1207
#define KEY_SOCKET0_PCIE7_MAX_SPEED  0x1208
#define KEY_SOCKET0_PCIE8_MAX_SPEED  0x1209
#define KEY_SOCKET0_PCIE9_MAX_SPEED  0x120A
#define KEY_SOCKET1_PCIE0_MAX_SPEED  0x120B
#define KEY_SOCKET1_PCIE1_MAX_SPEED  0x120C
#define KEY_SOCKET1_PCIE2_MAX_SPEED  0x120D
#define KEY_SOCKET1_PCIE3_MAX_SPEED  0x120E
#define KEY_SOCKET1_PCIE4_MAX_SPEED  0x120F
#define KEY_SOCKET1_PCIE5_MAX_SPEED  0x1210
#define KEY_SOCKET1_PCIE6_MAX_SPEED  0x1211
#define KEY_SOCKET1_PCIE7_MAX_SPEED  0x1212
#define KEY_SOCKET1_PCIE8_MAX_SPEED  0x1213
#define KEY_SOCKET1_PCIE9_MAX_SPEED  0x1214
#define KEY_SOCKET2_PCIE0_MAX_SPEED  0x1215
#define KEY_SOCKET2_PCIE1_MAX_SPEED  0x1216
#define KEY_SOCKET2_PCIE2_MAX_SPEED  0x1217
#define KEY_SOCKET2_PCIE3_MAX_SPEED  0x1218
#define KEY_SOCKET2_PCIE4_MAX_SPEED  0x1219
#define KEY_SOCKET2_PCIE5_MAX_SPEED  0x121A
#define KEY_SOCKET2_PCIE6_MAX_SPEED  0x121B
#define KEY_SOCKET2_PCIE7_MAX_SPEED  0x121C
#define KEY_SOCKET2_PCIE8_MAX_SPEED  0x121D
#define KEY_SOCKET2_PCIE9_MAX_SPEED  0x121E
#define KEY_SOCKET3_PCIE0_MAX_SPEED  0x121F
#define KEY_SOCKET3_PCIE1_MAX_SPEED  0x1220
#define KEY_SOCKET3_PCIE2_MAX_SPEED  0x1221
#define KEY_SOCKET3_PCIE3_MAX_SPEED  0x1222
#define KEY_SOCKET3_PCIE4_MAX_SPEED  0x1223
#define KEY_SOCKET3_PCIE5_MAX_SPEED  0x1224
#define KEY_SOCKET3_PCIE6_MAX_SPEED  0x1225
#define KEY_SOCKET3_PCIE7_MAX_SPEED  0x1226
#define KEY_SOCKET3_PCIE8_MAX_SPEED  0x1227
#define KEY_SOCKET3_PCIE9_MAX_SPEED  0x1228

#define KEY_SOCKET0_PCIE0_MAX_WIDTH  0x1301
#define KEY_SOCKET0_PCIE1_MAX_WIDTH  0x1302
#define KEY_SOCKET0_PCIE2_MAX_WIDTH  0x1303
#define KEY_SOCKET0_PCIE3_MAX_WIDTH  0x1304
#define KEY_SOCKET0_PCIE4_MAX_WIDTH  0x1305
#define KEY_SOCKET0_PCIE5_MAX_WIDTH  0x1306
#define KEY_SOCKET0_PCIE6_MAX_WIDTH  0x1307
#define KEY_SOCKET0_PCIE7_MAX_WIDTH  0x1308
#define KEY_SOCKET0_PCIE8_MAX_WIDTH  0x1309
#define KEY_SOCKET0_PCIE9_MAX_WIDTH  0x130A
#define KEY_SOCKET1_PCIE0_MAX_WIDTH  0x130B
#define KEY_SOCKET1_PCIE1_MAX_WIDTH  0x130C
#define KEY_SOCKET1_PCIE2_MAX_WIDTH  0x130D
#define KEY_SOCKET1_PCIE3_MAX_WIDTH  0x130E
#define KEY_SOCKET1_PCIE4_MAX_WIDTH  0x130F
#define KEY_SOCKET1_PCIE5_MAX_WIDTH  0x1310
#define KEY_SOCKET1_PCIE6_MAX_WIDTH  0x1311
#define KEY_SOCKET1_PCIE7_MAX_WIDTH  0x1312
#define KEY_SOCKET1_PCIE8_MAX_WIDTH  0x1313
#define KEY_SOCKET1_PCIE9_MAX_WIDTH  0x1314
#define KEY_SOCKET2_PCIE0_MAX_WIDTH  0x1315
#define KEY_SOCKET2_PCIE1_MAX_WIDTH  0x1316
#define KEY_SOCKET2_PCIE2_MAX_WIDTH  0x1317
#define KEY_SOCKET2_PCIE3_MAX_WIDTH  0x1318
#define KEY_SOCKET2_PCIE4_MAX_WIDTH  0x1319
#define KEY_SOCKET2_PCIE5_MAX_WIDTH  0x131A
#define KEY_SOCKET2_PCIE6_MAX_WIDTH  0x131B
#define KEY_SOCKET2_PCIE7_MAX_WIDTH  0x131C
#define KEY_SOCKET2_PCIE8_MAX_WIDTH  0x131D
#define KEY_SOCKET2_PCIE9_MAX_WIDTH  0x131E
#define KEY_SOCKET3_PCIE0_MAX_WIDTH  0x131F
#define KEY_SOCKET3_PCIE1_MAX_WIDTH  0x1320
#define KEY_SOCKET3_PCIE2_MAX_WIDTH  0x1321
#define KEY_SOCKET3_PCIE3_MAX_WIDTH  0x1322
#define KEY_SOCKET3_PCIE4_MAX_WIDTH  0x1323
#define KEY_SOCKET3_PCIE5_MAX_WIDTH  0x1324
#define KEY_SOCKET3_PCIE6_MAX_WIDTH  0x1325
#define KEY_SOCKET3_PCIE7_MAX_WIDTH  0x1326
#define KEY_SOCKET3_PCIE8_MAX_WIDTH  0x1327
#define KEY_SOCKET3_PCIE9_MAX_WIDTH  0x1328

#define KEY_SOCKET0_PCIE0_ADVERTISE_ASPML1  0x1401
#define KEY_SOCKET0_PCIE1_ADVERTISE_ASPML1  0x1402
#define KEY_SOCKET0_PCIE2_ADVERTISE_ASPML1  0x1403
#define KEY_SOCKET0_PCIE3_ADVERTISE_ASPML1  0x1404
#define KEY_SOCKET0_PCIE4_ADVERTISE_ASPML1  0x1405
#define KEY_SOCKET0_PCIE5_ADVERTISE_ASPML1  0x1406
#define KEY_SOCKET0_PCIE6_ADVERTISE_ASPML1  0x1407
#define KEY_SOCKET0_PCIE7_ADVERTISE_ASPML1  0x1408
#define KEY_SOCKET0_PCIE8_ADVERTISE_ASPML1  0x1409
#define KEY_SOCKET0_PCIE9_ADVERTISE_ASPML1  0x140A
#define KEY_SOCKET1_PCIE0_ADVERTISE_ASPML1  0x140B
#define KEY_SOCKET1_PCIE1_ADVERTISE_ASPML1  0x140C
#define KEY_SOCKET1_PCIE2_ADVERTISE_ASPML1  0x140D
#define KEY_SOCKET1_PCIE3_ADVERTISE_ASPML1  0x140E
#define KEY_SOCKET1_PCIE4_ADVERTISE_ASPML1  0x140F
#define KEY_SOCKET1_PCIE5_ADVERTISE_ASPML1  0x1410
#define KEY_SOCKET1_PCIE6_ADVERTISE_ASPML1  0x1411
#define KEY_SOCKET1_PCIE7_ADVERTISE_ASPML1  0x1412
#define KEY_SOCKET1_PCIE8_ADVERTISE_ASPML1  0x1413
#define KEY_SOCKET1_PCIE9_ADVERTISE_ASPML1  0x1414
#define KEY_SOCKET2_PCIE0_ADVERTISE_ASPML1  0x1415
#define KEY_SOCKET2_PCIE1_ADVERTISE_ASPML1  0x1416
#define KEY_SOCKET2_PCIE2_ADVERTISE_ASPML1  0x1417
#define KEY_SOCKET2_PCIE3_ADVERTISE_ASPML1  0x1418
#define KEY_SOCKET2_PCIE4_ADVERTISE_ASPML1  0x1419
#define KEY_SOCKET2_PCIE5_ADVERTISE_ASPML1  0x141A
#define KEY_SOCKET2_PCIE6_ADVERTISE_ASPML1  0x141B
#define KEY_SOCKET2_PCIE7_ADVERTISE_ASPML1  0x141C
#define KEY_SOCKET2_PCIE8_ADVERTISE_ASPML1  0x141D
#define KEY_SOCKET2_PCIE9_ADVERTISE_ASPML1  0x141E
#define KEY_SOCKET3_PCIE0_ADVERTISE_ASPML1  0x141F
#define KEY_SOCKET3_PCIE1_ADVERTISE_ASPML1  0x1420
#define KEY_SOCKET3_PCIE2_ADVERTISE_ASPML1  0x1421
#define KEY_SOCKET3_PCIE3_ADVERTISE_ASPML1  0x1422
#define KEY_SOCKET3_PCIE4_ADVERTISE_ASPML1  0x1423
#define KEY_SOCKET3_PCIE5_ADVERTISE_ASPML1  0x1424
#define KEY_SOCKET3_PCIE6_ADVERTISE_ASPML1  0x1425
#define KEY_SOCKET3_PCIE7_ADVERTISE_ASPML1  0x1426
#define KEY_SOCKET3_PCIE8_ADVERTISE_ASPML1  0x1427
#define KEY_SOCKET3_PCIE9_ADVERTISE_ASPML1  0x1428

#define KEY_SOCKET0_PCIE0_ADVERTISE_ASPML1_1  0x1501
#define KEY_SOCKET0_PCIE1_ADVERTISE_ASPML1_1  0x1502
#define KEY_SOCKET0_PCIE2_ADVERTISE_ASPML1_1  0x1503
#define KEY_SOCKET0_PCIE3_ADVERTISE_ASPML1_1  0x1504
#define KEY_SOCKET0_PCIE4_ADVERTISE_ASPML1_1  0x1505
#define KEY_SOCKET0_PCIE5_ADVERTISE_ASPML1_1  0x1506
#define KEY_SOCKET0_PCIE6_ADVERTISE_ASPML1_1  0x1507
#define KEY_SOCKET0_PCIE7_ADVERTISE_ASPML1_1  0x1508
#define KEY_SOCKET0_PCIE8_ADVERTISE_ASPML1_1  0x1509
#define KEY_SOCKET0_PCIE9_ADVERTISE_ASPML1_1  0x150A
#define KEY_SOCKET1_PCIE0_ADVERTISE_ASPML1_1  0x150B
#define KEY_SOCKET1_PCIE1_ADVERTISE_ASPML1_1  0x150C
#define KEY_SOCKET1_PCIE2_ADVERTISE_ASPML1_1  0x150D
#define KEY_SOCKET1_PCIE3_ADVERTISE_ASPML1_1  0x150E
#define KEY_SOCKET1_PCIE4_ADVERTISE_ASPML1_1  0x150F
#define KEY_SOCKET1_PCIE5_ADVERTISE_ASPML1_1  0x1510
#define KEY_SOCKET1_PCIE6_ADVERTISE_ASPML1_1  0x1511
#define KEY_SOCKET1_PCIE7_ADVERTISE_ASPML1_1  0x1512
#define KEY_SOCKET1_PCIE8_ADVERTISE_ASPML1_1  0x1513
#define KEY_SOCKET1_PCIE9_ADVERTISE_ASPML1_1  0x1514
#define KEY_SOCKET2_PCIE0_ADVERTISE_ASPML1_1  0x1515
#define KEY_SOCKET2_PCIE1_ADVERTISE_ASPML1_1  0x1516
#define KEY_SOCKET2_PCIE2_ADVERTISE_ASPML1_1  0x1517
#define KEY_SOCKET2_PCIE3_ADVERTISE_ASPML1_1  0x1518
#define KEY_SOCKET2_PCIE4_ADVERTISE_ASPML1_1  0x1519
#define KEY_SOCKET2_PCIE5_ADVERTISE_ASPML1_1  0x151A
#define KEY_SOCKET2_PCIE6_ADVERTISE_ASPML1_1  0x151B
#define KEY_SOCKET2_PCIE7_ADVERTISE_ASPML1_1  0x151C
#define KEY_SOCKET2_PCIE8_ADVERTISE_ASPML1_1  0x151D
#define KEY_SOCKET2_PCIE9_ADVERTISE_ASPML1_1  0x151E
#define KEY_SOCKET3_PCIE0_ADVERTISE_ASPML1_1  0x151F
#define KEY_SOCKET3_PCIE1_ADVERTISE_ASPML1_1  0x1520
#define KEY_SOCKET3_PCIE2_ADVERTISE_ASPML1_1  0x1521
#define KEY_SOCKET3_PCIE3_ADVERTISE_ASPML1_1  0x1522
#define KEY_SOCKET3_PCIE4_ADVERTISE_ASPML1_1  0x1523
#define KEY_SOCKET3_PCIE5_ADVERTISE_ASPML1_1  0x1524
#define KEY_SOCKET3_PCIE6_ADVERTISE_ASPML1_1  0x1525
#define KEY_SOCKET3_PCIE7_ADVERTISE_ASPML1_1  0x1526
#define KEY_SOCKET3_PCIE8_ADVERTISE_ASPML1_1  0x1527
#define KEY_SOCKET3_PCIE9_ADVERTISE_ASPML1_1  0x1528

#define KEY_SOCKET0_PCIE0_ADVERTISE_ASPML1_2  0x1601
#define KEY_SOCKET0_PCIE1_ADVERTISE_ASPML1_2  0x1602
#define KEY_SOCKET0_PCIE2_ADVERTISE_ASPML1_2  0x1603
#define KEY_SOCKET0_PCIE3_ADVERTISE_ASPML1_2  0x1604
#define KEY_SOCKET0_PCIE4_ADVERTISE_ASPML1_2  0x1605
#define KEY_SOCKET0_PCIE5_ADVERTISE_ASPML1_2  0x1606
#define KEY_SOCKET0_PCIE6_ADVERTISE_ASPML1_2  0x1607
#define KEY_SOCKET0_PCIE7_ADVERTISE_ASPML1_2  0x1608
#define KEY_SOCKET0_PCIE8_ADVERTISE_ASPML1_2  0x1609
#define KEY_SOCKET0_PCIE9_ADVERTISE_ASPML1_2  0x160A
#define KEY_SOCKET1_PCIE0_ADVERTISE_ASPML1_2  0x160B
#define KEY_SOCKET1_PCIE1_ADVERTISE_ASPML1_2  0x160C
#define KEY_SOCKET1_PCIE2_ADVERTISE_ASPML1_2  0x160D
#define KEY_SOCKET1_PCIE3_ADVERTISE_ASPML1_2  0x160E
#define KEY_SOCKET1_PCIE4_ADVERTISE_ASPML1_2  0x160F
#define KEY_SOCKET1_PCIE5_ADVERTISE_ASPML1_2  0x1610
#define KEY_SOCKET1_PCIE6_ADVERTISE_ASPML1_2  0x1611
#define KEY_SOCKET1_PCIE7_ADVERTISE_ASPML1_2  0x1612
#define KEY_SOCKET1_PCIE8_ADVERTISE_ASPML1_2  0x1613
#define KEY_SOCKET1_PCIE9_ADVERTISE_ASPML1_2  0x1614
#define KEY_SOCKET2_PCIE0_ADVERTISE_ASPML1_2  0x1615
#define KEY_SOCKET2_PCIE1_ADVERTISE_ASPML1_2  0x1616
#define KEY_SOCKET2_PCIE2_ADVERTISE_ASPML1_2  0x1617
#define KEY_SOCKET2_PCIE3_ADVERTISE_ASPML1_2  0x1618
#define KEY_SOCKET2_PCIE4_ADVERTISE_ASPML1_2  0x1619
#define KEY_SOCKET2_PCIE5_ADVERTISE_ASPML1_2  0x161A
#define KEY_SOCKET2_PCIE6_ADVERTISE_ASPML1_2  0x161B
#define KEY_SOCKET2_PCIE7_ADVERTISE_ASPML1_2  0x161C
#define KEY_SOCKET2_PCIE8_ADVERTISE_ASPML1_2  0x161D
#define KEY_SOCKET2_PCIE9_ADVERTISE_ASPML1_2  0x161E
#define KEY_SOCKET3_PCIE0_ADVERTISE_ASPML1_2  0x161F
#define KEY_SOCKET3_PCIE1_ADVERTISE_ASPML1_2  0x1620
#define KEY_SOCKET3_PCIE2_ADVERTISE_ASPML1_2  0x1621
#define KEY_SOCKET3_PCIE3_ADVERTISE_ASPML1_2  0x1622
#define KEY_SOCKET3_PCIE4_ADVERTISE_ASPML1_2  0x1623
#define KEY_SOCKET3_PCIE5_ADVERTISE_ASPML1_2  0x1624
#define KEY_SOCKET3_PCIE6_ADVERTISE_ASPML1_2  0x1625
#define KEY_SOCKET3_PCIE7_ADVERTISE_ASPML1_2  0x1626
#define KEY_SOCKET3_PCIE8_ADVERTISE_ASPML1_2  0x1627
#define KEY_SOCKET3_PCIE9_ADVERTISE_ASPML1_2  0x1628

#define KEY_SOCKET0_PCIE0_ADVERTISE_PCIPML1_2  0x1701
#define KEY_SOCKET0_PCIE1_ADVERTISE_PCIPML1_2  0x1702
#define KEY_SOCKET0_PCIE2_ADVERTISE_PCIPML1_2  0x1703
#define KEY_SOCKET0_PCIE3_ADVERTISE_PCIPML1_2  0x1704
#define KEY_SOCKET0_PCIE4_ADVERTISE_PCIPML1_2  0x1705
#define KEY_SOCKET0_PCIE5_ADVERTISE_PCIPML1_2  0x1706
#define KEY_SOCKET0_PCIE6_ADVERTISE_PCIPML1_2  0x1707
#define KEY_SOCKET0_PCIE7_ADVERTISE_PCIPML1_2  0x1708
#define KEY_SOCKET0_PCIE8_ADVERTISE_PCIPML1_2  0x1709
#define KEY_SOCKET0_PCIE9_ADVERTISE_PCIPML1_2  0x170A
#define KEY_SOCKET1_PCIE0_ADVERTISE_PCIPML1_2  0x170B
#define KEY_SOCKET1_PCIE1_ADVERTISE_PCIPML1_2  0x170C
#define KEY_SOCKET1_PCIE2_ADVERTISE_PCIPML1_2  0x170D
#define KEY_SOCKET1_PCIE3_ADVERTISE_PCIPML1_2  0x170E
#define KEY_SOCKET1_PCIE4_ADVERTISE_PCIPML1_2  0x170F
#define KEY_SOCKET1_PCIE5_ADVERTISE_PCIPML1_2  0x1710
#define KEY_SOCKET1_PCIE6_ADVERTISE_PCIPML1_2  0x1711
#define KEY_SOCKET1_PCIE7_ADVERTISE_PCIPML1_2  0x1712
#define KEY_SOCKET1_PCIE8_ADVERTISE_PCIPML1_2  0x1713
#define KEY_SOCKET1_PCIE9_ADVERTISE_PCIPML1_2  0x1714
#define KEY_SOCKET2_PCIE0_ADVERTISE_PCIPML1_2  0x1715
#define KEY_SOCKET2_PCIE1_ADVERTISE_PCIPML1_2  0x1716
#define KEY_SOCKET2_PCIE2_ADVERTISE_PCIPML1_2  0x1717
#define KEY_SOCKET2_PCIE3_ADVERTISE_PCIPML1_2  0x1718
#define KEY_SOCKET2_PCIE4_ADVERTISE_PCIPML1_2  0x1719
#define KEY_SOCKET2_PCIE5_ADVERTISE_PCIPML1_2  0x171A
#define KEY_SOCKET2_PCIE6_ADVERTISE_PCIPML1_2  0x171B
#define KEY_SOCKET2_PCIE7_ADVERTISE_PCIPML1_2  0x171C
#define KEY_SOCKET2_PCIE8_ADVERTISE_PCIPML1_2  0x171D
#define KEY_SOCKET2_PCIE9_ADVERTISE_PCIPML1_2  0x171E
#define KEY_SOCKET3_PCIE0_ADVERTISE_PCIPML1_2  0x171F
#define KEY_SOCKET3_PCIE1_ADVERTISE_PCIPML1_2  0x1720
#define KEY_SOCKET3_PCIE2_ADVERTISE_PCIPML1_2  0x1721
#define KEY_SOCKET3_PCIE3_ADVERTISE_PCIPML1_2  0x1722
#define KEY_SOCKET3_PCIE4_ADVERTISE_PCIPML1_2  0x1723
#define KEY_SOCKET3_PCIE5_ADVERTISE_PCIPML1_2  0x1724
#define KEY_SOCKET3_PCIE6_ADVERTISE_PCIPML1_2  0x1725
#define KEY_SOCKET3_PCIE7_ADVERTISE_PCIPML1_2  0x1726
#define KEY_SOCKET3_PCIE8_ADVERTISE_PCIPML1_2  0x1727
#define KEY_SOCKET3_PCIE9_ADVERTISE_PCIPML1_2  0x1728

#define KEY_SOCKET0_PCIE0_CLK_REQ  0x1801
#define KEY_SOCKET0_PCIE1_CLK_REQ  0x1802
#define KEY_SOCKET0_PCIE2_CLK_REQ  0x1803
#define KEY_SOCKET0_PCIE3_CLK_REQ  0x1804
#define KEY_SOCKET0_PCIE4_CLK_REQ  0x1805
#define KEY_SOCKET0_PCIE5_CLK_REQ  0x1806
#define KEY_SOCKET0_PCIE6_CLK_REQ  0x1807
#define KEY_SOCKET0_PCIE7_CLK_REQ  0x1808
#define KEY_SOCKET0_PCIE8_CLK_REQ  0x1809
#define KEY_SOCKET0_PCIE9_CLK_REQ  0x180A
#define KEY_SOCKET1_PCIE0_CLK_REQ  0x180B
#define KEY_SOCKET1_PCIE1_CLK_REQ  0x180C
#define KEY_SOCKET1_PCIE2_CLK_REQ  0x180D
#define KEY_SOCKET1_PCIE3_CLK_REQ  0x180E
#define KEY_SOCKET1_PCIE4_CLK_REQ  0x180F
#define KEY_SOCKET1_PCIE5_CLK_REQ  0x1810
#define KEY_SOCKET1_PCIE6_CLK_REQ  0x1811
#define KEY_SOCKET1_PCIE7_CLK_REQ  0x1812
#define KEY_SOCKET1_PCIE8_CLK_REQ  0x1813
#define KEY_SOCKET1_PCIE9_CLK_REQ  0x1814
#define KEY_SOCKET2_PCIE0_CLK_REQ  0x1815
#define KEY_SOCKET2_PCIE1_CLK_REQ  0x1816
#define KEY_SOCKET2_PCIE2_CLK_REQ  0x1817
#define KEY_SOCKET2_PCIE3_CLK_REQ  0x1818
#define KEY_SOCKET2_PCIE4_CLK_REQ  0x1819
#define KEY_SOCKET2_PCIE5_CLK_REQ  0x181A
#define KEY_SOCKET2_PCIE6_CLK_REQ  0x181B
#define KEY_SOCKET2_PCIE7_CLK_REQ  0x181C
#define KEY_SOCKET2_PCIE8_CLK_REQ  0x181D
#define KEY_SOCKET2_PCIE9_CLK_REQ  0x181E
#define KEY_SOCKET3_PCIE0_CLK_REQ  0x181F
#define KEY_SOCKET3_PCIE1_CLK_REQ  0x1820
#define KEY_SOCKET3_PCIE2_CLK_REQ  0x1821
#define KEY_SOCKET3_PCIE3_CLK_REQ  0x1822
#define KEY_SOCKET3_PCIE4_CLK_REQ  0x1823
#define KEY_SOCKET3_PCIE5_CLK_REQ  0x1824
#define KEY_SOCKET3_PCIE6_CLK_REQ  0x1825
#define KEY_SOCKET3_PCIE7_CLK_REQ  0x1826
#define KEY_SOCKET3_PCIE8_CLK_REQ  0x1827
#define KEY_SOCKET3_PCIE9_CLK_REQ  0x1828

#define KEY_SOCKET0_PCIE0_DISABLE_DLFE  0x1901
#define KEY_SOCKET0_PCIE1_DISABLE_DLFE  0x1902
#define KEY_SOCKET0_PCIE2_DISABLE_DLFE  0x1903
#define KEY_SOCKET0_PCIE3_DISABLE_DLFE  0x1904
#define KEY_SOCKET0_PCIE4_DISABLE_DLFE  0x1905
#define KEY_SOCKET0_PCIE5_DISABLE_DLFE  0x1906
#define KEY_SOCKET0_PCIE6_DISABLE_DLFE  0x1907
#define KEY_SOCKET0_PCIE7_DISABLE_DLFE  0x1908
#define KEY_SOCKET0_PCIE8_DISABLE_DLFE  0x1909
#define KEY_SOCKET0_PCIE9_DISABLE_DLFE  0x190A
#define KEY_SOCKET1_PCIE0_DISABLE_DLFE  0x190B
#define KEY_SOCKET1_PCIE1_DISABLE_DLFE  0x190C
#define KEY_SOCKET1_PCIE2_DISABLE_DLFE  0x190D
#define KEY_SOCKET1_PCIE3_DISABLE_DLFE  0x190E
#define KEY_SOCKET1_PCIE4_DISABLE_DLFE  0x190F
#define KEY_SOCKET1_PCIE5_DISABLE_DLFE  0x1910
#define KEY_SOCKET1_PCIE6_DISABLE_DLFE  0x1911
#define KEY_SOCKET1_PCIE7_DISABLE_DLFE  0x1912
#define KEY_SOCKET1_PCIE8_DISABLE_DLFE  0x1913
#define KEY_SOCKET1_PCIE9_DISABLE_DLFE  0x1914
#define KEY_SOCKET2_PCIE0_DISABLE_DLFE  0x1915
#define KEY_SOCKET2_PCIE1_DISABLE_DLFE  0x1916
#define KEY_SOCKET2_PCIE2_DISABLE_DLFE  0x1917
#define KEY_SOCKET2_PCIE3_DISABLE_DLFE  0x1918
#define KEY_SOCKET2_PCIE4_DISABLE_DLFE  0x1919
#define KEY_SOCKET2_PCIE5_DISABLE_DLFE  0x191A
#define KEY_SOCKET2_PCIE6_DISABLE_DLFE  0x191B
#define KEY_SOCKET2_PCIE7_DISABLE_DLFE  0x191C
#define KEY_SOCKET2_PCIE8_DISABLE_DLFE  0x191D
#define KEY_SOCKET2_PCIE9_DISABLE_DLFE  0x191E
#define KEY_SOCKET3_PCIE0_DISABLE_DLFE  0x191F
#define KEY_SOCKET3_PCIE1_DISABLE_DLFE  0x1920
#define KEY_SOCKET3_PCIE2_DISABLE_DLFE  0x1921
#define KEY_SOCKET3_PCIE3_DISABLE_DLFE  0x1922
#define KEY_SOCKET3_PCIE4_DISABLE_DLFE  0x1923
#define KEY_SOCKET3_PCIE5_DISABLE_DLFE  0x1924
#define KEY_SOCKET3_PCIE6_DISABLE_DLFE  0x1925
#define KEY_SOCKET3_PCIE7_DISABLE_DLFE  0x1926
#define KEY_SOCKET3_PCIE8_DISABLE_DLFE  0x1927
#define KEY_SOCKET3_PCIE9_DISABLE_DLFE  0x1928

#define KEY_SOCKET0_PCIE0_ENABLE_ECRC  0x1A01
#define KEY_SOCKET0_PCIE1_ENABLE_ECRC  0x1A02
#define KEY_SOCKET0_PCIE2_ENABLE_ECRC  0x1A03
#define KEY_SOCKET0_PCIE3_ENABLE_ECRC  0x1A04
#define KEY_SOCKET0_PCIE4_ENABLE_ECRC  0x1A05
#define KEY_SOCKET0_PCIE5_ENABLE_ECRC  0x1A06
#define KEY_SOCKET0_PCIE6_ENABLE_ECRC  0x1A07
#define KEY_SOCKET0_PCIE7_ENABLE_ECRC  0x1A08
#define KEY_SOCKET0_PCIE8_ENABLE_ECRC  0x1A09
#define KEY_SOCKET0_PCIE9_ENABLE_ECRC  0x1A0A
#define KEY_SOCKET1_PCIE0_ENABLE_ECRC  0x1A0B
#define KEY_SOCKET1_PCIE1_ENABLE_ECRC  0x1A0C
#define KEY_SOCKET1_PCIE2_ENABLE_ECRC  0x1A0D
#define KEY_SOCKET1_PCIE3_ENABLE_ECRC  0x1A0E
#define KEY_SOCKET1_PCIE4_ENABLE_ECRC  0x1A0F
#define KEY_SOCKET1_PCIE5_ENABLE_ECRC  0x1A10
#define KEY_SOCKET1_PCIE6_ENABLE_ECRC  0x1A11
#define KEY_SOCKET1_PCIE7_ENABLE_ECRC  0x1A12
#define KEY_SOCKET1_PCIE8_ENABLE_ECRC  0x1A13
#define KEY_SOCKET1_PCIE9_ENABLE_ECRC  0x1A14
#define KEY_SOCKET2_PCIE0_ENABLE_ECRC  0x1A15
#define KEY_SOCKET2_PCIE1_ENABLE_ECRC  0x1A16
#define KEY_SOCKET2_PCIE2_ENABLE_ECRC  0x1A17
#define KEY_SOCKET2_PCIE3_ENABLE_ECRC  0x1A18
#define KEY_SOCKET2_PCIE4_ENABLE_ECRC  0x1A19
#define KEY_SOCKET2_PCIE5_ENABLE_ECRC  0x1A1A
#define KEY_SOCKET2_PCIE6_ENABLE_ECRC  0x1A1B
#define KEY_SOCKET2_PCIE7_ENABLE_ECRC  0x1A1C
#define KEY_SOCKET2_PCIE8_ENABLE_ECRC  0x1A1D
#define KEY_SOCKET2_PCIE9_ENABLE_ECRC  0x1A1E
#define KEY_SOCKET3_PCIE0_ENABLE_ECRC  0x1A1F
#define KEY_SOCKET3_PCIE1_ENABLE_ECRC  0x1A20
#define KEY_SOCKET3_PCIE2_ENABLE_ECRC  0x1A21
#define KEY_SOCKET3_PCIE3_ENABLE_ECRC  0x1A22
#define KEY_SOCKET3_PCIE4_ENABLE_ECRC  0x1A23
#define KEY_SOCKET3_PCIE5_ENABLE_ECRC  0x1A24
#define KEY_SOCKET3_PCIE6_ENABLE_ECRC  0x1A25
#define KEY_SOCKET3_PCIE7_ENABLE_ECRC  0x1A26
#define KEY_SOCKET3_PCIE8_ENABLE_ECRC  0x1A27
#define KEY_SOCKET3_PCIE9_ENABLE_ECRC  0x1A28

#define KEY_SOCKET0_PCIE0_DISABLE_OPT_ROM  0x1B01
#define KEY_SOCKET0_PCIE1_DISABLE_OPT_ROM  0x1B02
#define KEY_SOCKET0_PCIE2_DISABLE_OPT_ROM  0x1B03
#define KEY_SOCKET0_PCIE3_DISABLE_OPT_ROM  0x1B04
#define KEY_SOCKET0_PCIE4_DISABLE_OPT_ROM  0x1B05
#define KEY_SOCKET0_PCIE5_DISABLE_OPT_ROM  0x1B06
#define KEY_SOCKET0_PCIE6_DISABLE_OPT_ROM  0x1B07
#define KEY_SOCKET0_PCIE7_DISABLE_OPT_ROM  0x1B08
#define KEY_SOCKET0_PCIE8_DISABLE_OPT_ROM  0x1B09
#define KEY_SOCKET0_PCIE9_DISABLE_OPT_ROM  0x1B0A
#define KEY_SOCKET1_PCIE0_DISABLE_OPT_ROM  0x1B0B
#define KEY_SOCKET1_PCIE1_DISABLE_OPT_ROM  0x1B0C
#define KEY_SOCKET1_PCIE2_DISABLE_OPT_ROM  0x1B0D
#define KEY_SOCKET1_PCIE3_DISABLE_OPT_ROM  0x1B0E
#define KEY_SOCKET1_PCIE4_DISABLE_OPT_ROM  0x1B0F
#define KEY_SOCKET1_PCIE5_DISABLE_OPT_ROM  0x1B10
#define KEY_SOCKET1_PCIE6_DISABLE_OPT_ROM  0x1B11
#define KEY_SOCKET1_PCIE7_DISABLE_OPT_ROM  0x1B12
#define KEY_SOCKET1_PCIE8_DISABLE_OPT_ROM  0x1B13
#define KEY_SOCKET1_PCIE9_DISABLE_OPT_ROM  0x1B14
#define KEY_SOCKET2_PCIE0_DISABLE_OPT_ROM  0x1B15
#define KEY_SOCKET2_PCIE1_DISABLE_OPT_ROM  0x1B16
#define KEY_SOCKET2_PCIE2_DISABLE_OPT_ROM  0x1B17
#define KEY_SOCKET2_PCIE3_DISABLE_OPT_ROM  0x1B18
#define KEY_SOCKET2_PCIE4_DISABLE_OPT_ROM  0x1B19
#define KEY_SOCKET2_PCIE5_DISABLE_OPT_ROM  0x1B1A
#define KEY_SOCKET2_PCIE6_DISABLE_OPT_ROM  0x1B1B
#define KEY_SOCKET2_PCIE7_DISABLE_OPT_ROM  0x1B1C
#define KEY_SOCKET2_PCIE8_DISABLE_OPT_ROM  0x1B1D
#define KEY_SOCKET2_PCIE9_DISABLE_OPT_ROM  0x1B1E
#define KEY_SOCKET3_PCIE0_DISABLE_OPT_ROM  0x1B1F
#define KEY_SOCKET3_PCIE1_DISABLE_OPT_ROM  0x1B20
#define KEY_SOCKET3_PCIE2_DISABLE_OPT_ROM  0x1B21
#define KEY_SOCKET3_PCIE3_DISABLE_OPT_ROM  0x1B22
#define KEY_SOCKET3_PCIE4_DISABLE_OPT_ROM  0x1B23
#define KEY_SOCKET3_PCIE5_DISABLE_OPT_ROM  0x1B24
#define KEY_SOCKET3_PCIE6_DISABLE_OPT_ROM  0x1B25
#define KEY_SOCKET3_PCIE7_DISABLE_OPT_ROM  0x1B26
#define KEY_SOCKET3_PCIE8_DISABLE_OPT_ROM  0x1B27
#define KEY_SOCKET3_PCIE9_DISABLE_OPT_ROM  0x1B28

#define KEY_SOCKET0_PCIE0_DISABLE_DPC_AT_RP  0x1C01
#define KEY_SOCKET0_PCIE1_DISABLE_DPC_AT_RP  0x1C02
#define KEY_SOCKET0_PCIE2_DISABLE_DPC_AT_RP  0x1C03
#define KEY_SOCKET0_PCIE3_DISABLE_DPC_AT_RP  0x1C04
#define KEY_SOCKET0_PCIE4_DISABLE_DPC_AT_RP  0x1C05
#define KEY_SOCKET0_PCIE5_DISABLE_DPC_AT_RP  0x1C06
#define KEY_SOCKET0_PCIE6_DISABLE_DPC_AT_RP  0x1C07
#define KEY_SOCKET0_PCIE7_DISABLE_DPC_AT_RP  0x1C08
#define KEY_SOCKET0_PCIE8_DISABLE_DPC_AT_RP  0x1C09
#define KEY_SOCKET0_PCIE9_DISABLE_DPC_AT_RP  0x1C0A
#define KEY_SOCKET1_PCIE0_DISABLE_DPC_AT_RP  0x1C0B
#define KEY_SOCKET1_PCIE1_DISABLE_DPC_AT_RP  0x1C0C
#define KEY_SOCKET1_PCIE2_DISABLE_DPC_AT_RP  0x1C0D
#define KEY_SOCKET1_PCIE3_DISABLE_DPC_AT_RP  0x1C0E
#define KEY_SOCKET1_PCIE4_DISABLE_DPC_AT_RP  0x1C0F
#define KEY_SOCKET1_PCIE5_DISABLE_DPC_AT_RP  0x1C10
#define KEY_SOCKET1_PCIE6_DISABLE_DPC_AT_RP  0x1C11
#define KEY_SOCKET1_PCIE7_DISABLE_DPC_AT_RP  0x1C12
#define KEY_SOCKET1_PCIE8_DISABLE_DPC_AT_RP  0x1C13
#define KEY_SOCKET1_PCIE9_DISABLE_DPC_AT_RP  0x1C14
#define KEY_SOCKET2_PCIE0_DISABLE_DPC_AT_RP  0x1C15
#define KEY_SOCKET2_PCIE1_DISABLE_DPC_AT_RP  0x1C16
#define KEY_SOCKET2_PCIE2_DISABLE_DPC_AT_RP  0x1C17
#define KEY_SOCKET2_PCIE3_DISABLE_DPC_AT_RP  0x1C18
#define KEY_SOCKET2_PCIE4_DISABLE_DPC_AT_RP  0x1C19
#define KEY_SOCKET2_PCIE5_DISABLE_DPC_AT_RP  0x1C1A
#define KEY_SOCKET2_PCIE6_DISABLE_DPC_AT_RP  0x1C1B
#define KEY_SOCKET2_PCIE7_DISABLE_DPC_AT_RP  0x1C1C
#define KEY_SOCKET2_PCIE8_DISABLE_DPC_AT_RP  0x1C1D
#define KEY_SOCKET2_PCIE9_DISABLE_DPC_AT_RP  0x1C1E
#define KEY_SOCKET3_PCIE0_DISABLE_DPC_AT_RP  0x1C1F
#define KEY_SOCKET3_PCIE1_DISABLE_DPC_AT_RP  0x1C20
#define KEY_SOCKET3_PCIE2_DISABLE_DPC_AT_RP  0x1C21
#define KEY_SOCKET3_PCIE3_DISABLE_DPC_AT_RP  0x1C22
#define KEY_SOCKET3_PCIE4_DISABLE_DPC_AT_RP  0x1C23
#define KEY_SOCKET3_PCIE5_DISABLE_DPC_AT_RP  0x1C24
#define KEY_SOCKET3_PCIE6_DISABLE_DPC_AT_RP  0x1C25
#define KEY_SOCKET3_PCIE7_DISABLE_DPC_AT_RP  0x1C26
#define KEY_SOCKET3_PCIE8_DISABLE_DPC_AT_RP  0x1C27
#define KEY_SOCKET3_PCIE9_DISABLE_DPC_AT_RP  0x1C28

#define KEY_SOCKET0_PCIE0_SLOT_NUM  0x1D01
#define KEY_SOCKET0_PCIE1_SLOT_NUM  0x1D02
#define KEY_SOCKET0_PCIE2_SLOT_NUM  0x1D03
#define KEY_SOCKET0_PCIE3_SLOT_NUM  0x1D04
#define KEY_SOCKET0_PCIE4_SLOT_NUM  0x1D05
#define KEY_SOCKET0_PCIE5_SLOT_NUM  0x1D06
#define KEY_SOCKET0_PCIE6_SLOT_NUM  0x1D07
#define KEY_SOCKET0_PCIE7_SLOT_NUM  0x1D08
#define KEY_SOCKET0_PCIE8_SLOT_NUM  0x1D09
#define KEY_SOCKET0_PCIE9_SLOT_NUM  0x1D0A
#define KEY_SOCKET1_PCIE0_SLOT_NUM  0x1D0B
#define KEY_SOCKET1_PCIE1_SLOT_NUM  0x1D0C
#define KEY_SOCKET1_PCIE2_SLOT_NUM  0x1D0D
#define KEY_SOCKET1_PCIE3_SLOT_NUM  0x1D0E
#define KEY_SOCKET1_PCIE4_SLOT_NUM  0x1D0F
#define KEY_SOCKET1_PCIE5_SLOT_NUM  0x1D10
#define KEY_SOCKET1_PCIE6_SLOT_NUM  0x1D11
#define KEY_SOCKET1_PCIE7_SLOT_NUM  0x1D12
#define KEY_SOCKET1_PCIE8_SLOT_NUM  0x1D13
#define KEY_SOCKET1_PCIE9_SLOT_NUM  0x1D14
#define KEY_SOCKET2_PCIE0_SLOT_NUM  0x1D15
#define KEY_SOCKET2_PCIE1_SLOT_NUM  0x1D16
#define KEY_SOCKET2_PCIE2_SLOT_NUM  0x1D17
#define KEY_SOCKET2_PCIE3_SLOT_NUM  0x1D18
#define KEY_SOCKET2_PCIE4_SLOT_NUM  0x1D19
#define KEY_SOCKET2_PCIE5_SLOT_NUM  0x1D1A
#define KEY_SOCKET2_PCIE6_SLOT_NUM  0x1D1B
#define KEY_SOCKET2_PCIE7_SLOT_NUM  0x1D1C
#define KEY_SOCKET2_PCIE8_SLOT_NUM  0x1D1D
#define KEY_SOCKET2_PCIE9_SLOT_NUM  0x1D1E
#define KEY_SOCKET3_PCIE0_SLOT_NUM  0x1D1F
#define KEY_SOCKET3_PCIE1_SLOT_NUM  0x1D20
#define KEY_SOCKET3_PCIE2_SLOT_NUM  0x1D21
#define KEY_SOCKET3_PCIE3_SLOT_NUM  0x1D22
#define KEY_SOCKET3_PCIE4_SLOT_NUM  0x1D23
#define KEY_SOCKET3_PCIE5_SLOT_NUM  0x1D24
#define KEY_SOCKET3_PCIE6_SLOT_NUM  0x1D25
#define KEY_SOCKET3_PCIE7_SLOT_NUM  0x1D26
#define KEY_SOCKET3_PCIE8_SLOT_NUM  0x1D27
#define KEY_SOCKET3_PCIE9_SLOT_NUM  0x1D28

#define KEY_SOCKET0_PCIE0_MASK_UNSUPPORTED_REQUEST  0x1E01
#define KEY_SOCKET0_PCIE1_MASK_UNSUPPORTED_REQUEST  0x1E02
#define KEY_SOCKET0_PCIE2_MASK_UNSUPPORTED_REQUEST  0x1E03
#define KEY_SOCKET0_PCIE3_MASK_UNSUPPORTED_REQUEST  0x1E04
#define KEY_SOCKET0_PCIE4_MASK_UNSUPPORTED_REQUEST  0x1E05
#define KEY_SOCKET0_PCIE5_MASK_UNSUPPORTED_REQUEST  0x1E06
#define KEY_SOCKET0_PCIE6_MASK_UNSUPPORTED_REQUEST  0x1E07
#define KEY_SOCKET0_PCIE7_MASK_UNSUPPORTED_REQUEST  0x1E08
#define KEY_SOCKET0_PCIE8_MASK_UNSUPPORTED_REQUEST  0x1E09
#define KEY_SOCKET0_PCIE9_MASK_UNSUPPORTED_REQUEST  0x1E0A
#define KEY_SOCKET1_PCIE0_MASK_UNSUPPORTED_REQUEST  0x1E0B
#define KEY_SOCKET1_PCIE1_MASK_UNSUPPORTED_REQUEST  0x1E0C
#define KEY_SOCKET1_PCIE2_MASK_UNSUPPORTED_REQUEST  0x1E0D
#define KEY_SOCKET1_PCIE3_MASK_UNSUPPORTED_REQUEST  0x1E0E
#define KEY_SOCKET1_PCIE4_MASK_UNSUPPORTED_REQUEST  0x1E0F
#define KEY_SOCKET1_PCIE5_MASK_UNSUPPORTED_REQUEST  0x1E10
#define KEY_SOCKET1_PCIE6_MASK_UNSUPPORTED_REQUEST  0x1E11
#define KEY_SOCKET1_PCIE7_MASK_UNSUPPORTED_REQUEST  0x1E12
#define KEY_SOCKET1_PCIE8_MASK_UNSUPPORTED_REQUEST  0x1E13
#define KEY_SOCKET1_PCIE9_MASK_UNSUPPORTED_REQUEST  0x1E14
#define KEY_SOCKET2_PCIE0_MASK_UNSUPPORTED_REQUEST  0x1E15
#define KEY_SOCKET2_PCIE1_MASK_UNSUPPORTED_REQUEST  0x1E16
#define KEY_SOCKET2_PCIE2_MASK_UNSUPPORTED_REQUEST  0x1E17
#define KEY_SOCKET2_PCIE3_MASK_UNSUPPORTED_REQUEST  0x1E18
#define KEY_SOCKET2_PCIE4_MASK_UNSUPPORTED_REQUEST  0x1E19
#define KEY_SOCKET2_PCIE5_MASK_UNSUPPORTED_REQUEST  0x1E1A
#define KEY_SOCKET2_PCIE6_MASK_UNSUPPORTED_REQUEST  0x1E1B
#define KEY_SOCKET2_PCIE7_MASK_UNSUPPORTED_REQUEST  0x1E1C
#define KEY_SOCKET2_PCIE8_MASK_UNSUPPORTED_REQUEST  0x1E1D
#define KEY_SOCKET2_PCIE9_MASK_UNSUPPORTED_REQUEST  0x1E1E
#define KEY_SOCKET3_PCIE0_MASK_UNSUPPORTED_REQUEST  0x1E1F
#define KEY_SOCKET3_PCIE1_MASK_UNSUPPORTED_REQUEST  0x1E20
#define KEY_SOCKET3_PCIE2_MASK_UNSUPPORTED_REQUEST  0x1E21
#define KEY_SOCKET3_PCIE3_MASK_UNSUPPORTED_REQUEST  0x1E22
#define KEY_SOCKET3_PCIE4_MASK_UNSUPPORTED_REQUEST  0x1E23
#define KEY_SOCKET3_PCIE5_MASK_UNSUPPORTED_REQUEST  0x1E24
#define KEY_SOCKET3_PCIE6_MASK_UNSUPPORTED_REQUEST  0x1E25
#define KEY_SOCKET3_PCIE7_MASK_UNSUPPORTED_REQUEST  0x1E26
#define KEY_SOCKET3_PCIE8_MASK_UNSUPPORTED_REQUEST  0x1E27
#define KEY_SOCKET3_PCIE9_MASK_UNSUPPORTED_REQUEST  0x1E28

#define KEY_SOCKET0_PCIE0_MASK_COMPLETER_ABORT  0x1F01
#define KEY_SOCKET0_PCIE1_MASK_COMPLETER_ABORT  0x1F02
#define KEY_SOCKET0_PCIE2_MASK_COMPLETER_ABORT  0x1F03
#define KEY_SOCKET0_PCIE3_MASK_COMPLETER_ABORT  0x1F04
#define KEY_SOCKET0_PCIE4_MASK_COMPLETER_ABORT  0x1F05
#define KEY_SOCKET0_PCIE5_MASK_COMPLETER_ABORT  0x1F06
#define KEY_SOCKET0_PCIE6_MASK_COMPLETER_ABORT  0x1F07
#define KEY_SOCKET0_PCIE7_MASK_COMPLETER_ABORT  0x1F08
#define KEY_SOCKET0_PCIE8_MASK_COMPLETER_ABORT  0x1F09
#define KEY_SOCKET0_PCIE9_MASK_COMPLETER_ABORT  0x1F0A
#define KEY_SOCKET1_PCIE0_MASK_COMPLETER_ABORT  0x1F0B
#define KEY_SOCKET1_PCIE1_MASK_COMPLETER_ABORT  0x1F0C
#define KEY_SOCKET1_PCIE2_MASK_COMPLETER_ABORT  0x1F0D
#define KEY_SOCKET1_PCIE3_MASK_COMPLETER_ABORT  0x1F0E
#define KEY_SOCKET1_PCIE4_MASK_COMPLETER_ABORT  0x1F0F
#define KEY_SOCKET1_PCIE5_MASK_COMPLETER_ABORT  0x1F10
#define KEY_SOCKET1_PCIE6_MASK_COMPLETER_ABORT  0x1F11
#define KEY_SOCKET1_PCIE7_MASK_COMPLETER_ABORT  0x1F12
#define KEY_SOCKET1_PCIE8_MASK_COMPLETER_ABORT  0x1F13
#define KEY_SOCKET1_PCIE9_MASK_COMPLETER_ABORT  0x1F14
#define KEY_SOCKET2_PCIE0_MASK_COMPLETER_ABORT  0x1F15
#define KEY_SOCKET2_PCIE1_MASK_COMPLETER_ABORT  0x1F16
#define KEY_SOCKET2_PCIE2_MASK_COMPLETER_ABORT  0x1F17
#define KEY_SOCKET2_PCIE3_MASK_COMPLETER_ABORT  0x1F18
#define KEY_SOCKET2_PCIE4_MASK_COMPLETER_ABORT  0x1F19
#define KEY_SOCKET2_PCIE5_MASK_COMPLETER_ABORT  0x1F1A
#define KEY_SOCKET2_PCIE6_MASK_COMPLETER_ABORT  0x1F1B
#define KEY_SOCKET2_PCIE7_MASK_COMPLETER_ABORT  0x1F1C
#define KEY_SOCKET2_PCIE8_MASK_COMPLETER_ABORT  0x1F1D
#define KEY_SOCKET2_PCIE9_MASK_COMPLETER_ABORT  0x1F1E
#define KEY_SOCKET3_PCIE0_MASK_COMPLETER_ABORT  0x1F1F
#define KEY_SOCKET3_PCIE1_MASK_COMPLETER_ABORT  0x1F20
#define KEY_SOCKET3_PCIE2_MASK_COMPLETER_ABORT  0x1F21
#define KEY_SOCKET3_PCIE3_MASK_COMPLETER_ABORT  0x1F22
#define KEY_SOCKET3_PCIE4_MASK_COMPLETER_ABORT  0x1F23
#define KEY_SOCKET3_PCIE5_MASK_COMPLETER_ABORT  0x1F24
#define KEY_SOCKET3_PCIE6_MASK_COMPLETER_ABORT  0x1F25
#define KEY_SOCKET3_PCIE7_MASK_COMPLETER_ABORT  0x1F26
#define KEY_SOCKET3_PCIE8_MASK_COMPLETER_ABORT  0x1F27
#define KEY_SOCKET3_PCIE9_MASK_COMPLETER_ABORT  0x1F28

#define KEY_SOCKET0_PCIE0_SUPPORTS_PRSNT  0x2001
#define KEY_SOCKET0_PCIE1_SUPPORTS_PRSNT  0x2002
#define KEY_SOCKET0_PCIE2_SUPPORTS_PRSNT  0x2003
#define KEY_SOCKET0_PCIE3_SUPPORTS_PRSNT  0x2004
#define KEY_SOCKET0_PCIE4_SUPPORTS_PRSNT  0x2005
#define KEY_SOCKET0_PCIE5_SUPPORTS_PRSNT  0x2006
#define KEY_SOCKET0_PCIE6_SUPPORTS_PRSNT  0x2007
#define KEY_SOCKET0_PCIE7_SUPPORTS_PRSNT  0x2008
#define KEY_SOCKET0_PCIE8_SUPPORTS_PRSNT  0x2009
#define KEY_SOCKET0_PCIE9_SUPPORTS_PRSNT  0x200A
#define KEY_SOCKET1_PCIE0_SUPPORTS_PRSNT  0x200B
#define KEY_SOCKET1_PCIE1_SUPPORTS_PRSNT  0x200C
#define KEY_SOCKET1_PCIE2_SUPPORTS_PRSNT  0x200D
#define KEY_SOCKET1_PCIE3_SUPPORTS_PRSNT  0x200E
#define KEY_SOCKET1_PCIE4_SUPPORTS_PRSNT  0x200F
#define KEY_SOCKET1_PCIE5_SUPPORTS_PRSNT  0x2010
#define KEY_SOCKET1_PCIE6_SUPPORTS_PRSNT  0x2011
#define KEY_SOCKET1_PCIE7_SUPPORTS_PRSNT  0x2012
#define KEY_SOCKET1_PCIE8_SUPPORTS_PRSNT  0x2013
#define KEY_SOCKET1_PCIE9_SUPPORTS_PRSNT  0x2014
#define KEY_SOCKET2_PCIE0_SUPPORTS_PRSNT  0x2015
#define KEY_SOCKET2_PCIE1_SUPPORTS_PRSNT  0x2016
#define KEY_SOCKET2_PCIE2_SUPPORTS_PRSNT  0x2017
#define KEY_SOCKET2_PCIE3_SUPPORTS_PRSNT  0x2018
#define KEY_SOCKET2_PCIE4_SUPPORTS_PRSNT  0x2019
#define KEY_SOCKET2_PCIE5_SUPPORTS_PRSNT  0x201A
#define KEY_SOCKET2_PCIE6_SUPPORTS_PRSNT  0x201B
#define KEY_SOCKET2_PCIE7_SUPPORTS_PRSNT  0x201C
#define KEY_SOCKET2_PCIE8_SUPPORTS_PRSNT  0x201D
#define KEY_SOCKET2_PCIE9_SUPPORTS_PRSNT  0x201E
#define KEY_SOCKET3_PCIE0_SUPPORTS_PRSNT  0x201F
#define KEY_SOCKET3_PCIE1_SUPPORTS_PRSNT  0x2020
#define KEY_SOCKET3_PCIE2_SUPPORTS_PRSNT  0x2021
#define KEY_SOCKET3_PCIE3_SUPPORTS_PRSNT  0x2022
#define KEY_SOCKET3_PCIE4_SUPPORTS_PRSNT  0x2023
#define KEY_SOCKET3_PCIE5_SUPPORTS_PRSNT  0x2024
#define KEY_SOCKET3_PCIE6_SUPPORTS_PRSNT  0x2025
#define KEY_SOCKET3_PCIE7_SUPPORTS_PRSNT  0x2026
#define KEY_SOCKET3_PCIE8_SUPPORTS_PRSNT  0x2027
#define KEY_SOCKET3_PCIE9_SUPPORTS_PRSNT  0x2028

#define KEY_SOCKET0_PCIE0_ADVERTISE_ACS  0x2101
#define KEY_SOCKET0_PCIE1_ADVERTISE_ACS  0x2102
#define KEY_SOCKET0_PCIE2_ADVERTISE_ACS  0x2103
#define KEY_SOCKET0_PCIE3_ADVERTISE_ACS  0x2104
#define KEY_SOCKET0_PCIE4_ADVERTISE_ACS  0x2105
#define KEY_SOCKET0_PCIE5_ADVERTISE_ACS  0x2106
#define KEY_SOCKET0_PCIE6_ADVERTISE_ACS  0x2107
#define KEY_SOCKET0_PCIE7_ADVERTISE_ACS  0x2108
#define KEY_SOCKET0_PCIE8_ADVERTISE_ACS  0x2109
#define KEY_SOCKET0_PCIE9_ADVERTISE_ACS  0x210A
#define KEY_SOCKET1_PCIE0_ADVERTISE_ACS  0x210B
#define KEY_SOCKET1_PCIE1_ADVERTISE_ACS  0x210C
#define KEY_SOCKET1_PCIE2_ADVERTISE_ACS  0x210D
#define KEY_SOCKET1_PCIE3_ADVERTISE_ACS  0x210E
#define KEY_SOCKET1_PCIE4_ADVERTISE_ACS  0x210F
#define KEY_SOCKET1_PCIE5_ADVERTISE_ACS  0x2110
#define KEY_SOCKET1_PCIE6_ADVERTISE_ACS  0x2111
#define KEY_SOCKET1_PCIE7_ADVERTISE_ACS  0x2112
#define KEY_SOCKET1_PCIE8_ADVERTISE_ACS  0x2113
#define KEY_SOCKET1_PCIE9_ADVERTISE_ACS  0x2114
#define KEY_SOCKET2_PCIE0_ADVERTISE_ACS  0x2115
#define KEY_SOCKET2_PCIE1_ADVERTISE_ACS  0x2116
#define KEY_SOCKET2_PCIE2_ADVERTISE_ACS  0x2117
#define KEY_SOCKET2_PCIE3_ADVERTISE_ACS  0x2118
#define KEY_SOCKET2_PCIE4_ADVERTISE_ACS  0x2119
#define KEY_SOCKET2_PCIE5_ADVERTISE_ACS  0x211A
#define KEY_SOCKET2_PCIE6_ADVERTISE_ACS  0x211B
#define KEY_SOCKET2_PCIE7_ADVERTISE_ACS  0x211C
#define KEY_SOCKET2_PCIE8_ADVERTISE_ACS  0x211D
#define KEY_SOCKET2_PCIE9_ADVERTISE_ACS  0x211E
#define KEY_SOCKET3_PCIE0_ADVERTISE_ACS  0x211F
#define KEY_SOCKET3_PCIE1_ADVERTISE_ACS  0x2120
#define KEY_SOCKET3_PCIE2_ADVERTISE_ACS  0x2121
#define KEY_SOCKET3_PCIE3_ADVERTISE_ACS  0x2122
#define KEY_SOCKET3_PCIE4_ADVERTISE_ACS  0x2123
#define KEY_SOCKET3_PCIE5_ADVERTISE_ACS  0x2124
#define KEY_SOCKET3_PCIE6_ADVERTISE_ACS  0x2125
#define KEY_SOCKET3_PCIE7_ADVERTISE_ACS  0x2126
#define KEY_SOCKET3_PCIE8_ADVERTISE_ACS  0x2127
#define KEY_SOCKET3_PCIE9_ADVERTISE_ACS  0x2128

#define KEY_SOCKET0_PCIE0_MAX_PAYLOAD_SIZE  0x2129
#define KEY_SOCKET0_PCIE1_MAX_PAYLOAD_SIZE  0x212A
#define KEY_SOCKET0_PCIE2_MAX_PAYLOAD_SIZE  0x212B
#define KEY_SOCKET0_PCIE3_MAX_PAYLOAD_SIZE  0x212C
#define KEY_SOCKET0_PCIE4_MAX_PAYLOAD_SIZE  0x212D
#define KEY_SOCKET0_PCIE5_MAX_PAYLOAD_SIZE  0x212E
#define KEY_SOCKET0_PCIE6_MAX_PAYLOAD_SIZE  0x212F
#define KEY_SOCKET0_PCIE7_MAX_PAYLOAD_SIZE  0x2130
#define KEY_SOCKET0_PCIE8_MAX_PAYLOAD_SIZE  0x2131
#define KEY_SOCKET0_PCIE9_MAX_PAYLOAD_SIZE  0x2132
#define KEY_SOCKET1_PCIE0_MAX_PAYLOAD_SIZE  0x2133
#define KEY_SOCKET1_PCIE1_MAX_PAYLOAD_SIZE  0x2134
#define KEY_SOCKET1_PCIE2_MAX_PAYLOAD_SIZE  0x2135
#define KEY_SOCKET1_PCIE3_MAX_PAYLOAD_SIZE  0x2136
#define KEY_SOCKET1_PCIE4_MAX_PAYLOAD_SIZE  0x2137
#define KEY_SOCKET1_PCIE5_MAX_PAYLOAD_SIZE  0x2138
#define KEY_SOCKET1_PCIE6_MAX_PAYLOAD_SIZE  0x2139
#define KEY_SOCKET1_PCIE7_MAX_PAYLOAD_SIZE  0x213A
#define KEY_SOCKET1_PCIE8_MAX_PAYLOAD_SIZE  0x213B
#define KEY_SOCKET1_PCIE9_MAX_PAYLOAD_SIZE  0x213C
#define KEY_SOCKET2_PCIE0_MAX_PAYLOAD_SIZE  0x213D
#define KEY_SOCKET2_PCIE1_MAX_PAYLOAD_SIZE  0x213E
#define KEY_SOCKET2_PCIE2_MAX_PAYLOAD_SIZE  0x213F
#define KEY_SOCKET2_PCIE3_MAX_PAYLOAD_SIZE  0x2140
#define KEY_SOCKET2_PCIE4_MAX_PAYLOAD_SIZE  0x2141
#define KEY_SOCKET2_PCIE5_MAX_PAYLOAD_SIZE  0x2142
#define KEY_SOCKET2_PCIE6_MAX_PAYLOAD_SIZE  0x2143
#define KEY_SOCKET2_PCIE7_MAX_PAYLOAD_SIZE  0x2144
#define KEY_SOCKET2_PCIE8_MAX_PAYLOAD_SIZE  0x2145
#define KEY_SOCKET2_PCIE9_MAX_PAYLOAD_SIZE  0x2146
#define KEY_SOCKET3_PCIE0_MAX_PAYLOAD_SIZE  0x2147
#define KEY_SOCKET3_PCIE1_MAX_PAYLOAD_SIZE  0x2148
#define KEY_SOCKET3_PCIE2_MAX_PAYLOAD_SIZE  0x2149
#define KEY_SOCKET3_PCIE3_MAX_PAYLOAD_SIZE  0x214A
#define KEY_SOCKET3_PCIE4_MAX_PAYLOAD_SIZE  0x214B
#define KEY_SOCKET3_PCIE5_MAX_PAYLOAD_SIZE  0x214C
#define KEY_SOCKET3_PCIE6_MAX_PAYLOAD_SIZE  0x214D
#define KEY_SOCKET3_PCIE7_MAX_PAYLOAD_SIZE  0x214E
#define KEY_SOCKET3_PCIE8_MAX_PAYLOAD_SIZE  0x214F
#define KEY_SOCKET3_PCIE9_MAX_PAYLOAD_SIZE  0x2150

#define KEY_SOCKET0_PCIE0_EXTENDED_10BIT_TAG_ENABLE  0x2151
#define KEY_SOCKET0_PCIE1_EXTENDED_10BIT_TAG_ENABLE  0x2152
#define KEY_SOCKET0_PCIE2_EXTENDED_10BIT_TAG_ENABLE  0x2153
#define KEY_SOCKET0_PCIE3_EXTENDED_10BIT_TAG_ENABLE  0x2154
#define KEY_SOCKET0_PCIE4_EXTENDED_10BIT_TAG_ENABLE  0x2155
#define KEY_SOCKET0_PCIE5_EXTENDED_10BIT_TAG_ENABLE  0x2156
#define KEY_SOCKET0_PCIE6_EXTENDED_10BIT_TAG_ENABLE  0x2157
#define KEY_SOCKET0_PCIE7_EXTENDED_10BIT_TAG_ENABLE  0x2158
#define KEY_SOCKET0_PCIE8_EXTENDED_10BIT_TAG_ENABLE  0x2159
#define KEY_SOCKET0_PCIE9_EXTENDED_10BIT_TAG_ENABLE  0x215A
#define KEY_SOCKET1_PCIE0_EXTENDED_10BIT_TAG_ENABLE  0x215B
#define KEY_SOCKET1_PCIE1_EXTENDED_10BIT_TAG_ENABLE  0x215C
#define KEY_SOCKET1_PCIE2_EXTENDED_10BIT_TAG_ENABLE  0x215D
#define KEY_SOCKET1_PCIE3_EXTENDED_10BIT_TAG_ENABLE  0x215E
#define KEY_SOCKET1_PCIE4_EXTENDED_10BIT_TAG_ENABLE  0x215F
#define KEY_SOCKET1_PCIE5_EXTENDED_10BIT_TAG_ENABLE  0x2160
#define KEY_SOCKET1_PCIE6_EXTENDED_10BIT_TAG_ENABLE  0x2161
#define KEY_SOCKET1_PCIE7_EXTENDED_10BIT_TAG_ENABLE  0x2162
#define KEY_SOCKET1_PCIE8_EXTENDED_10BIT_TAG_ENABLE  0x2163
#define KEY_SOCKET1_PCIE9_EXTENDED_10BIT_TAG_ENABLE  0x2164
#define KEY_SOCKET2_PCIE0_EXTENDED_10BIT_TAG_ENABLE  0x2165
#define KEY_SOCKET2_PCIE1_EXTENDED_10BIT_TAG_ENABLE  0x2166
#define KEY_SOCKET2_PCIE2_EXTENDED_10BIT_TAG_ENABLE  0x2167
#define KEY_SOCKET2_PCIE3_EXTENDED_10BIT_TAG_ENABLE  0x2168
#define KEY_SOCKET2_PCIE4_EXTENDED_10BIT_TAG_ENABLE  0x2169
#define KEY_SOCKET2_PCIE5_EXTENDED_10BIT_TAG_ENABLE  0x216A
#define KEY_SOCKET2_PCIE6_EXTENDED_10BIT_TAG_ENABLE  0x216B
#define KEY_SOCKET2_PCIE7_EXTENDED_10BIT_TAG_ENABLE  0x216C
#define KEY_SOCKET2_PCIE8_EXTENDED_10BIT_TAG_ENABLE  0x216D
#define KEY_SOCKET2_PCIE9_EXTENDED_10BIT_TAG_ENABLE  0x216E
#define KEY_SOCKET3_PCIE0_EXTENDED_10BIT_TAG_ENABLE  0x216F
#define KEY_SOCKET3_PCIE1_EXTENDED_10BIT_TAG_ENABLE  0x2170
#define KEY_SOCKET3_PCIE2_EXTENDED_10BIT_TAG_ENABLE  0x2171
#define KEY_SOCKET3_PCIE3_EXTENDED_10BIT_TAG_ENABLE  0x2172
#define KEY_SOCKET3_PCIE4_EXTENDED_10BIT_TAG_ENABLE  0x2173
#define KEY_SOCKET3_PCIE5_EXTENDED_10BIT_TAG_ENABLE  0x2174
#define KEY_SOCKET3_PCIE6_EXTENDED_10BIT_TAG_ENABLE  0x2175
#define KEY_SOCKET3_PCIE7_EXTENDED_10BIT_TAG_ENABLE  0x2176
#define KEY_SOCKET3_PCIE8_EXTENDED_10BIT_TAG_ENABLE  0x2177
#define KEY_SOCKET3_PCIE9_EXTENDED_10BIT_TAG_ENABLE  0x2178

#define KEY_SOCKET0_PCIE0_DELAY_AFTER_PERST  0x2179
#define KEY_SOCKET0_PCIE1_DELAY_AFTER_PERST  0x217A
#define KEY_SOCKET0_PCIE2_DELAY_AFTER_PERST  0x217B
#define KEY_SOCKET0_PCIE3_DELAY_AFTER_PERST  0x217C
#define KEY_SOCKET0_PCIE4_DELAY_AFTER_PERST  0x217D
#define KEY_SOCKET0_PCIE5_DELAY_AFTER_PERST  0x217E
#define KEY_SOCKET0_PCIE6_DELAY_AFTER_PERST  0x217F
#define KEY_SOCKET0_PCIE7_DELAY_AFTER_PERST  0x2180
#define KEY_SOCKET0_PCIE8_DELAY_AFTER_PERST  0x2181
#define KEY_SOCKET0_PCIE9_DELAY_AFTER_PERST  0x2182
#define KEY_SOCKET1_PCIE0_DELAY_AFTER_PERST  0x2183
#define KEY_SOCKET1_PCIE1_DELAY_AFTER_PERST  0x2184
#define KEY_SOCKET1_PCIE2_DELAY_AFTER_PERST  0x2185
#define KEY_SOCKET1_PCIE3_DELAY_AFTER_PERST  0x2186
#define KEY_SOCKET1_PCIE4_DELAY_AFTER_PERST  0x2187
#define KEY_SOCKET1_PCIE5_DELAY_AFTER_PERST  0x2188
#define KEY_SOCKET1_PCIE6_DELAY_AFTER_PERST  0x2189
#define KEY_SOCKET1_PCIE7_DELAY_AFTER_PERST  0x218A
#define KEY_SOCKET1_PCIE8_DELAY_AFTER_PERST  0x218B
#define KEY_SOCKET1_PCIE9_DELAY_AFTER_PERST  0x218C
#define KEY_SOCKET2_PCIE0_DELAY_AFTER_PERST  0x218D
#define KEY_SOCKET2_PCIE1_DELAY_AFTER_PERST  0x218E
#define KEY_SOCKET2_PCIE2_DELAY_AFTER_PERST  0x218F
#define KEY_SOCKET2_PCIE3_DELAY_AFTER_PERST  0x2190
#define KEY_SOCKET2_PCIE4_DELAY_AFTER_PERST  0x2191
#define KEY_SOCKET2_PCIE5_DELAY_AFTER_PERST  0x2192
#define KEY_SOCKET2_PCIE6_DELAY_AFTER_PERST  0x2193
#define KEY_SOCKET2_PCIE7_DELAY_AFTER_PERST  0x2194
#define KEY_SOCKET2_PCIE8_DELAY_AFTER_PERST  0x2195
#define KEY_SOCKET2_PCIE9_DELAY_AFTER_PERST  0x2196
#define KEY_SOCKET3_PCIE0_DELAY_AFTER_PERST  0x2197
#define KEY_SOCKET3_PCIE1_DELAY_AFTER_PERST  0x2198
#define KEY_SOCKET3_PCIE2_DELAY_AFTER_PERST  0x2199
#define KEY_SOCKET3_PCIE3_DELAY_AFTER_PERST  0x219A
#define KEY_SOCKET3_PCIE4_DELAY_AFTER_PERST  0x219B
#define KEY_SOCKET3_PCIE5_DELAY_AFTER_PERST  0x219C
#define KEY_SOCKET3_PCIE6_DELAY_AFTER_PERST  0x219D
#define KEY_SOCKET3_PCIE7_DELAY_AFTER_PERST  0x219E
#define KEY_SOCKET3_PCIE8_DELAY_AFTER_PERST  0x219F
#define KEY_SOCKET3_PCIE9_DELAY_AFTER_PERST  0x21A0

#define KEY_SOCKET0_PCIE0_OS_NATIVE_AER  0x2201
#define KEY_SOCKET0_PCIE1_OS_NATIVE_AER  0x2202
#define KEY_SOCKET0_PCIE2_OS_NATIVE_AER  0x2203
#define KEY_SOCKET0_PCIE3_OS_NATIVE_AER  0x2204
#define KEY_SOCKET0_PCIE4_OS_NATIVE_AER  0x2205
#define KEY_SOCKET0_PCIE5_OS_NATIVE_AER  0x2206
#define KEY_SOCKET0_PCIE6_OS_NATIVE_AER  0x2207
#define KEY_SOCKET0_PCIE7_OS_NATIVE_AER  0x2208
#define KEY_SOCKET0_PCIE8_OS_NATIVE_AER  0x2209
#define KEY_SOCKET0_PCIE9_OS_NATIVE_AER  0x220A
#define KEY_SOCKET1_PCIE0_OS_NATIVE_AER  0x220B
#define KEY_SOCKET1_PCIE1_OS_NATIVE_AER  0x220C
#define KEY_SOCKET1_PCIE2_OS_NATIVE_AER  0x220D
#define KEY_SOCKET1_PCIE3_OS_NATIVE_AER  0x220E
#define KEY_SOCKET1_PCIE4_OS_NATIVE_AER  0x220F
#define KEY_SOCKET1_PCIE5_OS_NATIVE_AER  0x2210
#define KEY_SOCKET1_PCIE6_OS_NATIVE_AER  0x2211
#define KEY_SOCKET1_PCIE7_OS_NATIVE_AER  0x2212
#define KEY_SOCKET1_PCIE8_OS_NATIVE_AER  0x2213
#define KEY_SOCKET1_PCIE9_OS_NATIVE_AER  0x2214
#define KEY_SOCKET2_PCIE0_OS_NATIVE_AER  0x2215
#define KEY_SOCKET2_PCIE1_OS_NATIVE_AER  0x2216
#define KEY_SOCKET2_PCIE2_OS_NATIVE_AER  0x2217
#define KEY_SOCKET2_PCIE3_OS_NATIVE_AER  0x2218
#define KEY_SOCKET2_PCIE4_OS_NATIVE_AER  0x2219
#define KEY_SOCKET2_PCIE5_OS_NATIVE_AER  0x221A
#define KEY_SOCKET2_PCIE6_OS_NATIVE_AER  0x221B
#define KEY_SOCKET2_PCIE7_OS_NATIVE_AER  0x221C
#define KEY_SOCKET2_PCIE8_OS_NATIVE_AER  0x221D
#define KEY_SOCKET2_PCIE9_OS_NATIVE_AER  0x221E
#define KEY_SOCKET3_PCIE0_OS_NATIVE_AER  0x221F
#define KEY_SOCKET3_PCIE1_OS_NATIVE_AER  0x2220
#define KEY_SOCKET3_PCIE2_OS_NATIVE_AER  0x2221
#define KEY_SOCKET3_PCIE3_OS_NATIVE_AER  0x2222
#define KEY_SOCKET3_PCIE4_OS_NATIVE_AER  0x2223
#define KEY_SOCKET3_PCIE5_OS_NATIVE_AER  0x2224
#define KEY_SOCKET3_PCIE6_OS_NATIVE_AER  0x2225
#define KEY_SOCKET3_PCIE7_OS_NATIVE_AER  0x2226
#define KEY_SOCKET3_PCIE8_OS_NATIVE_AER  0x2227
#define KEY_SOCKET3_PCIE9_OS_NATIVE_AER  0x2228

#define KEY_MPAM40_CPOR_WAYMASK  0x2300
#define KEY_MPAM41_CPOR_WAYMASK  0x2301
#define KEY_MPAM42_CPOR_WAYMASK  0x2302
#define KEY_MPAM43_CPOR_WAYMASK  0x2303
#define KEY_MPAM44_CPOR_WAYMASK  0x2304
#define KEY_MPAM40_MAX_BW        0x2305
#define KEY_MPAM41_MAX_BW        0x2306
#define KEY_MPAM42_MAX_BW        0x2307
#define KEY_MPAM43_MAX_BW        0x2308
#define KEY_MPAM44_MAX_BW        0x2309
#define KEY_MPAM40_MIN_BW        0x230A
#define KEY_MPAM41_MIN_BW        0x230B
#define KEY_MPAM42_MIN_BW        0x230C
#define KEY_MPAM43_MIN_BW        0x230D
#define KEY_MPAM44_MIN_BW        0x230E

#define KEY_SOCKET0_PCIE0_DISABLE_L23_AT_WARM_RESET  0x2401
#define KEY_SOCKET0_PCIE1_DISABLE_L23_AT_WARM_RESET  0x2402
#define KEY_SOCKET0_PCIE2_DISABLE_L23_AT_WARM_RESET  0x2403
#define KEY_SOCKET0_PCIE3_DISABLE_L23_AT_WARM_RESET  0x2404
#define KEY_SOCKET0_PCIE4_DISABLE_L23_AT_WARM_RESET  0x2405
#define KEY_SOCKET0_PCIE5_DISABLE_L23_AT_WARM_RESET  0x2406
#define KEY_SOCKET0_PCIE6_DISABLE_L23_AT_WARM_RESET  0x2407
#define KEY_SOCKET0_PCIE7_DISABLE_L23_AT_WARM_RESET  0x2408
#define KEY_SOCKET0_PCIE8_DISABLE_L23_AT_WARM_RESET  0x2409
#define KEY_SOCKET0_PCIE9_DISABLE_L23_AT_WARM_RESET  0x240A
#define KEY_SOCKET1_PCIE0_DISABLE_L23_AT_WARM_RESET  0x240B
#define KEY_SOCKET1_PCIE1_DISABLE_L23_AT_WARM_RESET  0x240C
#define KEY_SOCKET1_PCIE2_DISABLE_L23_AT_WARM_RESET  0x240D
#define KEY_SOCKET1_PCIE3_DISABLE_L23_AT_WARM_RESET  0x240E
#define KEY_SOCKET1_PCIE4_DISABLE_L23_AT_WARM_RESET  0x240F
#define KEY_SOCKET1_PCIE5_DISABLE_L23_AT_WARM_RESET  0x2410
#define KEY_SOCKET1_PCIE6_DISABLE_L23_AT_WARM_RESET  0x2411
#define KEY_SOCKET1_PCIE7_DISABLE_L23_AT_WARM_RESET  0x2412
#define KEY_SOCKET1_PCIE8_DISABLE_L23_AT_WARM_RESET  0x2413
#define KEY_SOCKET1_PCIE9_DISABLE_L23_AT_WARM_RESET  0x2414
#define KEY_SOCKET2_PCIE0_DISABLE_L23_AT_WARM_RESET  0x2415
#define KEY_SOCKET2_PCIE1_DISABLE_L23_AT_WARM_RESET  0x2416
#define KEY_SOCKET2_PCIE2_DISABLE_L23_AT_WARM_RESET  0x2417
#define KEY_SOCKET2_PCIE3_DISABLE_L23_AT_WARM_RESET  0x2418
#define KEY_SOCKET2_PCIE4_DISABLE_L23_AT_WARM_RESET  0x2419
#define KEY_SOCKET2_PCIE5_DISABLE_L23_AT_WARM_RESET  0x241A
#define KEY_SOCKET2_PCIE6_DISABLE_L23_AT_WARM_RESET  0x241B
#define KEY_SOCKET2_PCIE7_DISABLE_L23_AT_WARM_RESET  0x241C
#define KEY_SOCKET2_PCIE8_DISABLE_L23_AT_WARM_RESET  0x241D
#define KEY_SOCKET2_PCIE9_DISABLE_L23_AT_WARM_RESET  0x241E
#define KEY_SOCKET3_PCIE0_DISABLE_L23_AT_WARM_RESET  0x241F
#define KEY_SOCKET3_PCIE1_DISABLE_L23_AT_WARM_RESET  0x2420
#define KEY_SOCKET3_PCIE2_DISABLE_L23_AT_WARM_RESET  0x2421
#define KEY_SOCKET3_PCIE3_DISABLE_L23_AT_WARM_RESET  0x2422
#define KEY_SOCKET3_PCIE4_DISABLE_L23_AT_WARM_RESET  0x2423
#define KEY_SOCKET3_PCIE5_DISABLE_L23_AT_WARM_RESET  0x2424
#define KEY_SOCKET3_PCIE6_DISABLE_L23_AT_WARM_RESET  0x2425
#define KEY_SOCKET3_PCIE7_DISABLE_L23_AT_WARM_RESET  0x2426
#define KEY_SOCKET3_PCIE8_DISABLE_L23_AT_WARM_RESET  0x2427
#define KEY_SOCKET3_PCIE9_DISABLE_L23_AT_WARM_RESET  0x2428

#define KEY_SOCKET0_PCIE0_OS_NATIVE_PME  0x2501
#define KEY_SOCKET0_PCIE1_OS_NATIVE_PME  0x2502
#define KEY_SOCKET0_PCIE2_OS_NATIVE_PME  0x2503
#define KEY_SOCKET0_PCIE3_OS_NATIVE_PME  0x2504
#define KEY_SOCKET0_PCIE4_OS_NATIVE_PME  0x2505
#define KEY_SOCKET0_PCIE5_OS_NATIVE_PME  0x2506
#define KEY_SOCKET0_PCIE6_OS_NATIVE_PME  0x2507
#define KEY_SOCKET0_PCIE7_OS_NATIVE_PME  0x2508
#define KEY_SOCKET0_PCIE8_OS_NATIVE_PME  0x2509
#define KEY_SOCKET0_PCIE9_OS_NATIVE_PME  0x250A
#define KEY_SOCKET1_PCIE0_OS_NATIVE_PME  0x250B
#define KEY_SOCKET1_PCIE1_OS_NATIVE_PME  0x250C
#define KEY_SOCKET1_PCIE2_OS_NATIVE_PME  0x250D
#define KEY_SOCKET1_PCIE3_OS_NATIVE_PME  0x250E
#define KEY_SOCKET1_PCIE4_OS_NATIVE_PME  0x250F
#define KEY_SOCKET1_PCIE5_OS_NATIVE_PME  0x2510
#define KEY_SOCKET1_PCIE6_OS_NATIVE_PME  0x2511
#define KEY_SOCKET1_PCIE7_OS_NATIVE_PME  0x2512
#define KEY_SOCKET1_PCIE8_OS_NATIVE_PME  0x2513
#define KEY_SOCKET1_PCIE9_OS_NATIVE_PME  0x2514
#define KEY_SOCKET2_PCIE0_OS_NATIVE_PME  0x2515
#define KEY_SOCKET2_PCIE1_OS_NATIVE_PME  0x2516
#define KEY_SOCKET2_PCIE2_OS_NATIVE_PME  0x2517
#define KEY_SOCKET2_PCIE3_OS_NATIVE_PME  0x2518
#define KEY_SOCKET2_PCIE4_OS_NATIVE_PME  0x2519
#define KEY_SOCKET2_PCIE5_OS_NATIVE_PME  0x251A
#define KEY_SOCKET2_PCIE6_OS_NATIVE_PME  0x251B
#define KEY_SOCKET2_PCIE7_OS_NATIVE_PME  0x251C
#define KEY_SOCKET2_PCIE8_OS_NATIVE_PME  0x251D
#define KEY_SOCKET2_PCIE9_OS_NATIVE_PME  0x251E
#define KEY_SOCKET3_PCIE0_OS_NATIVE_PME  0x251F
#define KEY_SOCKET3_PCIE1_OS_NATIVE_PME  0x2520
#define KEY_SOCKET3_PCIE2_OS_NATIVE_PME  0x2521
#define KEY_SOCKET3_PCIE3_OS_NATIVE_PME  0x2522
#define KEY_SOCKET3_PCIE4_OS_NATIVE_PME  0x2523
#define KEY_SOCKET3_PCIE5_OS_NATIVE_PME  0x2524
#define KEY_SOCKET3_PCIE6_OS_NATIVE_PME  0x2525
#define KEY_SOCKET3_PCIE7_OS_NATIVE_PME  0x2526
#define KEY_SOCKET3_PCIE8_OS_NATIVE_PME  0x2527
#define KEY_SOCKET3_PCIE9_OS_NATIVE_PME  0x2528

#define LABEL_DBG2_PCIE_DEVICE_START  0x3000
#define LABEL_DBG2_PCIE_DEVICE_END    0x3001
#define MAX_DBG2_STRING_LENGTH        128

#define NVIDIA_CONFIG_HII_CONTROL_ID  0x1000

#define PCIE_IN_OS_DISABLE  0x0
#define PCIE_IN_OS_ENABLE   0x1

#define QUICK_BOOT_DISABLE  0x0
#define QUICK_BOOT_ENABLE   0x1

#define IPMI_NETWORK_BOOT_MODE_IPV4  0x0
#define IPMI_NETWORK_BOOT_MODE_IPV6  0x1

#define ACPI_TIMER_DISABLE  0x0
#define ACPI_TIMER_ENABLE   0x1

#define HOST_INTERFACE_DISABLE  0x0
#define HOST_INTERFACE_ENABLE   0x1

#define NEW_DEVICE_HIERARCHY_BOTTOM  0x0
#define NEW_DEVICE_HIERARCHY_TOP     0x1

#define DGPU_DT_EFIFB_DISABLE  0x0
#define DGPU_DT_EFIFB_ENABLE   0x1

#define ASSET_TAG_PROTECTION_DISABLE  0x0
#define ASSET_TAG_PROTECTION_ENABLE   0x1

#define MAX_SOCKETS         4
#define MAX_PCIE            10
#define MAX_UPHY            6
#define MAX_MPAM_PARTID     45
#define MPAM_PARTID_OFFSET  40

#define EXPOSE_PCIE_FLOORSWEEPING_VARIABLE          0x0001
#define EXPOSE_NVML_FLOORSWEEPING_VARIABLE          0x0002
#define EXPOSE_C2C_FLOORSWEEPING_VARIABLE           0x0004
#define EXPOSE_HALF_CHIP_DISABLED_VARIABLE          0x0008
#define EXPOSE_MCF_CHANNEL_DISABLED_VARIABLE        0x0010
#define EXPOSE_UPHY_LANE_OWNERSHIP_VARAIBLE         0x0020
#define EXPOSE_CCPLEX_CORE_DISABLED_VARIABLE        0x0040
#define EXPOSE_CCPLEX_MCF_BRIDGE_DISABLED_VARIABLE  0x0080
#define EXPOSE_CCPLEX_SOC_BRIDGE_DISABLED_VARIABLE  0x0100
#define EXPOSE_CCPLEX_CSN_DISABLED_VARIABLE         0x0200
#define EXPOSE_SCF_CACHE_DISABLED_VARIABLE          0x0400

#define UART_BAUD_RATE_115200  0
#define UART_BAUD_RATE_57600   1
#define UART_BAUD_RATE_38400   2
#define UART_BAUD_RATE_19200   3
#define UART_BAUD_RATE_9600    4
#define UART_BAUD_RATE_MAX     5

#define PERF_VERSION_DEFAULT  0
#define PERF_VERSION_C1_NCM   1

#define POWER_CTL_INPUT_PWR_CAPPING_50MS  0
#define POWER_CTL_INPUT_PWR_CAPPING_1S    1
#define POWER_CTL_INPUT_PWR_CAPPING_5S    2

#define ECC_ALGORITHM_HSIAO  0
#define ECC_ALGORITHM_RS     1

#define MAX_ALLOWED_0_SPARES  0
#define MAX_ALLOWED_1_SPARES  1
#define MAX_ALLOWED_2_SPARES  2

typedef struct {
  UINT32     L4TSupported;
  BOOLEAN    QuickBootSupported;
  BOOLEAN    DebugMenuSupported;
  BOOLEAN    RedfishSupported;
  BOOLEAN    ModsSpEnableSettingSupported;
  BOOLEAN    TpmEnableSettingSupported;
  BOOLEAN    GpuSmmuBypassEnableSettingSupported;
  BOOLEAN    UartBaudRateSettingSupported;
  BOOLEAN    PerfVersionSettingSupported;
  BOOLEAN    EInjEnableSupported;
  BOOLEAN    DisableChannelSparingSupported;
  BOOLEAN    EccAlgorithmSupported;
  BOOLEAN    MaxAllowedNumSparesSupported;
  BOOLEAN    DisplayAllMaxAllowedNumSparesOptions;
  BOOLEAN    PCIeASPML1SSConfigSupported;
  BOOLEAN    PCIeSlotNumConfigSupported;
  BOOLEAN    PCIeURCAConfigSupported;
  BOOLEAN    PCIePRSNTConfigSupported;
  BOOLEAN    PCIeACSConfigSupported;
  BOOLEAN    PCIeOSNativeAERSupported;
  BOOLEAN    PCIeOSNativePMESupported;
  BOOLEAN    PCIeDisableL23AtWarmResetSupported;
  BOOLEAN    MemoryTestsSupported;
  BOOLEAN    ActiveCoresSettingSupported;
  BOOLEAN    ServerPwrCtlSettingSupported;
  BOOLEAN    MpamPartidConfigSupported;
  BOOLEAN    HvEgmSizeSupported;
  UINT32     RootfsRedundancyLevel;
  UINT32     Dbg2NetworkDevice;
  BOOLEAN    TH500Config;
  BOOLEAN    SocketEnabled[MAX_SOCKETS];
  UINT8      PhysicalPcieWidth0[MAX_PCIE];
  UINT8      PhysicalPcieWidth1[MAX_PCIE];
  UINT8      PhysicalPcieWidth2[MAX_PCIE];
  UINT8      PhysicalPcieWidth3[MAX_PCIE];
  // MB1 DATA
  BOOLEAN    EgmEnabled;
  UINT32     EgmHvSizeMb;
  UINT32     HvMinEgmSize;
  UINT32     HvVirtUefiSize;
  UINT32     UefiDebugLevel;
  BOOLEAN    SpreadSpectrumEnable;
  BOOLEAN    ModsSpEnable;
  BOOLEAN    TpmPresent;
  UINT8      TpmEnable;
  BOOLEAN    GpuSmmuBypassEnable;
  UINT8      UartBaudRate;
  UINT8      PerfVersion;
  BOOLEAN    EInjEnable;
  BOOLEAN    DisableChannelSparing;
  UINT8      EccAlgorithm;
  UINT8      MaxAllowedNumSpares;
  UINT32     ActiveCores;
  UINT8      UphySetting0[MAX_UPHY];
  UINT8      UphySetting1[MAX_UPHY];
  UINT8      UphySetting2[MAX_UPHY];
  UINT8      UphySetting3[MAX_UPHY];
  UINT32     MaxSpeed0[MAX_PCIE];
  UINT32     MaxSpeed1[MAX_PCIE];
  UINT32     MaxSpeed2[MAX_PCIE];
  UINT32     MaxSpeed3[MAX_PCIE];
  UINT32     MaxWidth0[MAX_PCIE];
  UINT32     MaxWidth1[MAX_PCIE];
  UINT32     MaxWidth2[MAX_PCIE];
  UINT32     MaxWidth3[MAX_PCIE];
  UINT8      SlotType0[MAX_PCIE];
  UINT8      SlotType1[MAX_PCIE];
  UINT8      SlotType2[MAX_PCIE];
  UINT8      SlotType3[MAX_PCIE];
  UINT16     SlotNum0[MAX_PCIE];
  UINT16     SlotNum1[MAX_PCIE];
  UINT16     SlotNum2[MAX_PCIE];
  UINT16     SlotNum3[MAX_PCIE];
  UINT8      MaxPayloadSize0[MAX_PCIE];
  UINT8      MaxPayloadSize1[MAX_PCIE];
  UINT8      MaxPayloadSize2[MAX_PCIE];
  UINT8      MaxPayloadSize3[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_0[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_1[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_2[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_3[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_1_0[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_1_1[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_1_2[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_1_3[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_2_0[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_2_1[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_2_2[MAX_PCIE];
  BOOLEAN    AdvertiseAspmL1_2_3[MAX_PCIE];
  BOOLEAN    AdvertisePciPmL1_2_0[MAX_PCIE];
  BOOLEAN    AdvertisePciPmL1_2_1[MAX_PCIE];
  BOOLEAN    AdvertisePciPmL1_2_2[MAX_PCIE];
  BOOLEAN    AdvertisePciPmL1_2_3[MAX_PCIE];
  BOOLEAN    SupportsClkReq0[MAX_PCIE];
  BOOLEAN    SupportsClkReq1[MAX_PCIE];
  BOOLEAN    SupportsClkReq2[MAX_PCIE];
  BOOLEAN    SupportsClkReq3[MAX_PCIE];
  BOOLEAN    DisableDLFE0[MAX_PCIE];
  BOOLEAN    DisableDLFE1[MAX_PCIE];
  BOOLEAN    DisableDLFE2[MAX_PCIE];
  BOOLEAN    DisableDLFE3[MAX_PCIE];
  BOOLEAN    EnableECRC_0[MAX_PCIE];
  BOOLEAN    EnableECRC_1[MAX_PCIE];
  BOOLEAN    EnableECRC_2[MAX_PCIE];
  BOOLEAN    EnableECRC_3[MAX_PCIE];
  BOOLEAN    DisableOptionRom0[MAX_PCIE];
  BOOLEAN    DisableOptionRom1[MAX_PCIE];
  BOOLEAN    DisableOptionRom2[MAX_PCIE];
  BOOLEAN    DisableOptionRom3[MAX_PCIE];
  BOOLEAN    DisableDPCAtRP_0[MAX_PCIE];
  BOOLEAN    DisableDPCAtRP_1[MAX_PCIE];
  BOOLEAN    DisableDPCAtRP_2[MAX_PCIE];
  BOOLEAN    DisableDPCAtRP_3[MAX_PCIE];
  BOOLEAN    MaskUnsupportedRequest_0[MAX_PCIE];
  BOOLEAN    MaskUnsupportedRequest_1[MAX_PCIE];
  BOOLEAN    MaskUnsupportedRequest_2[MAX_PCIE];
  BOOLEAN    MaskUnsupportedRequest_3[MAX_PCIE];
  BOOLEAN    MaskCompleterAbort_0[MAX_PCIE];
  BOOLEAN    MaskCompleterAbort_1[MAX_PCIE];
  BOOLEAN    MaskCompleterAbort_2[MAX_PCIE];
  BOOLEAN    MaskCompleterAbort_3[MAX_PCIE];
  BOOLEAN    SupportsPRSNT_0[MAX_PCIE];
  BOOLEAN    SupportsPRSNT_1[MAX_PCIE];
  BOOLEAN    SupportsPRSNT_2[MAX_PCIE];
  BOOLEAN    SupportsPRSNT_3[MAX_PCIE];
  BOOLEAN    AdvertiseACS_0[MAX_PCIE];
  BOOLEAN    AdvertiseACS_1[MAX_PCIE];
  BOOLEAN    AdvertiseACS_2[MAX_PCIE];
  BOOLEAN    AdvertiseACS_3[MAX_PCIE];
  BOOLEAN    Extended10bitTagEnable0[MAX_PCIE];
  BOOLEAN    Extended10bitTagEnable1[MAX_PCIE];
  BOOLEAN    Extended10bitTagEnable2[MAX_PCIE];
  BOOLEAN    Extended10bitTagEnable3[MAX_PCIE];
  BOOLEAN    OsNativeAER_0[MAX_PCIE];
  BOOLEAN    OsNativeAER_1[MAX_PCIE];
  BOOLEAN    OsNativeAER_2[MAX_PCIE];
  BOOLEAN    OsNativeAER_3[MAX_PCIE];
  BOOLEAN    OsNativePME_0[MAX_PCIE];
  BOOLEAN    OsNativePME_1[MAX_PCIE];
  BOOLEAN    OsNativePME_2[MAX_PCIE];
  BOOLEAN    OsNativePME_3[MAX_PCIE];
  UINT16     CporWayMask[MAX_MPAM_PARTID];
  UINT8      MaxBw[MAX_MPAM_PARTID];
  UINT8      MinBw[MAX_MPAM_PARTID];
  BOOLEAN    DisableL23AtWarmReset_0[MAX_PCIE];
  BOOLEAN    DisableL23AtWarmReset_1[MAX_PCIE];
  BOOLEAN    DisableL23AtWarmReset_2[MAX_PCIE];
  BOOLEAN    DisableL23AtWarmReset_3[MAX_PCIE];
  UINT8      DelayAfterPERST0[MAX_PCIE];
  UINT8      DelayAfterPERST1[MAX_PCIE];
  UINT8      DelayAfterPERST2[MAX_PCIE];
  UINT8      DelayAfterPERST3[MAX_PCIE];
  BOOLEAN    NvDisplayHandoffControlSupported;
} NVIDIA_CONFIG_HII_CONTROL;

#define ADD_GOTO_SOCKET_FORM(socket)                                       \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.SocketEnabled[socket] == 0; \
  goto TH500_SOCKET##socket##_CONFIGURATION_FORM_ID,                       \
      prompt = STRING_TOKEN(STR_SOCKET##socket##_CONFIG_FORM_TITLE),       \
      help = STRING_TOKEN(STR_SOCKET##socket##_CONFIG_FORM_HELP);          \
  endif;

#define ADD_GOTO_PCIE_FORM(socket, pcie)                          \
  goto TH500_SOCKET##socket##_PCIE##pcie##_CONFIGURATION_FORM_ID, \
      prompt = STRING_TOKEN(STR_PCIE##pcie##_CONFIG_FORM_TITLE),  \
      help = STRING_TOKEN(STR_NULL);

#define ADD_GOTO_MPAM_FORM(mpam)                                       \
  goto TH500_MPAM##mpam##_CONFIGURATION_FORM_ID,                       \
      prompt = STRING_TOKEN(STR_MPAM##mpam##_CONFIG_FORM_TITLE),       \
      help = STRING_TOKEN(STR_NULL);

#define ADD_MPAM_FORM(mpam)                                                       \
  form formid = TH500_MPAM##mpam##_CONFIGURATION_FORM_ID,                         \
       title = STRING_TOKEN(STR_MPAM##mpam##_CONFIG_FORM_TITLE);                  \
  subtitle text = STRING_TOKEN(STR_NULL);                                         \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.MpamPartidConfigSupported == 0;    \
  numeric varid = NVIDIA_CONFIG_HII_CONTROL.CporWayMask[mpam],                    \
          questionid = KEY_MPAM##mpam##_CPOR_WAYMASK,                             \
          prompt = STRING_TOKEN(STR_MPAM##mpam##_CPOR_WAYMASK_TITLE),             \
          help = STRING_TOKEN(STR_MPAM##mpam##_CPOR_WAYMASK_HELP),                \
          flags = INTERACTIVE | RESET_REQUIRED | DISPLAY_UINT_HEX,                \
          minimum = 0,                                                            \
          maximum = 4095,                                                         \
          step = 1,                                                               \
          default = 4095,                                                         \
          endnumeric;                                                             \
  numeric varid = NVIDIA_CONFIG_HII_CONTROL.MaxBw[mpam],                          \
          questionid = KEY_MPAM##mpam##_MAX_BW,                                   \
          prompt = STRING_TOKEN(STR_MPAM##mpam##_MAX_BW_TITLE),                   \
          help = STRING_TOKEN(STR_MPAM##mpam##_MAX_BW_HELP),                      \
          flags = INTERACTIVE | RESET_REQUIRED | DISPLAY_UINT_DEC,                \
          minimum = 0,                                                            \
          maximum = 100,                                                          \
          step = 1,                                                               \
          default = 100,                                                          \
          endnumeric;                                                             \
   numeric varid = NVIDIA_CONFIG_HII_CONTROL.MinBw[mpam],                         \
          questionid = KEY_MPAM##mpam##_MIN_BW,                                   \
          prompt = STRING_TOKEN(STR_MPAM##mpam##_MIN_BW_TITLE),                   \
          help = STRING_TOKEN(STR_MPAM##mpam##_MIN_BW_HELP),                      \
          flags = INTERACTIVE | RESET_REQUIRED | DISPLAY_UINT_DEC,                \
          minimum = 0,                                                            \
          maximum = 100,                                                          \
          step = 1,                                                               \
          default = 100,                                                          \
          endnumeric;                                                             \
  endif;                                                                          \
  endform;

#define ADD_SOCKET_FORM(socket)                                                          \
  form formid = TH500_SOCKET##socket##_CONFIGURATION_FORM_ID,                            \
       title = STRING_TOKEN(STR_SOCKET##socket##_CONFIG_FORM_TITLE);                     \
  subtitle text = STRING_TOKEN(STR_NULL);                                                \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.SocketEnabled[socket] == 0;               \
  oneof varid = NVIDIA_CONFIG_HII_CONTROL.UphySetting##socket[0],                        \
        questionid = KEY_UPHY0_SOCKET##socket##_CONFIG,                                  \
        prompt = STRING_TOKEN(STR_UPHY0_SOCKET##socket##_PROMPT),                        \
        help = STRING_TOKEN(STR_UPHY0_HELP),                                             \
        flags = INTERACTIVE | RESET_REQUIRED,                                            \
        option text = STRING_TOKEN(STR_DISABLED), value = 0, flags = 0;                  \
        option text = STRING_TOKEN(STR_PCIE_C0_X16), value = 1, flags = 0;               \
        option text = STRING_TOKEN(STR_PCIE_C0_X8_C1_X8), value = 2, flags = 0;          \
  endoneof;                                                                              \
  ADD_GOTO_PCIE_FORM(socket, 0)                                                          \
  ADD_GOTO_PCIE_FORM(socket, 1)                                                          \
  oneof varid = NVIDIA_CONFIG_HII_CONTROL.UphySetting##socket[1],                        \
        questionid = KEY_UPHY1_SOCKET##socket##_CONFIG,                                  \
        prompt = STRING_TOKEN(STR_UPHY1_SOCKET##socket##_PROMPT),                        \
        help = STRING_TOKEN(STR_UPHY1_HELP),                                             \
        flags = INTERACTIVE | RESET_REQUIRED,                                            \
        option text = STRING_TOKEN(STR_DISABLED), value = 0, flags = 0;                  \
        option text = STRING_TOKEN(STR_PCIE_C2_X16), value = 1, flags = 0;               \
        option text = STRING_TOKEN(STR_PCIE_C2_X8_C3_X8), value = 2, flags = 0;          \
  endoneof;                                                                              \
  ADD_GOTO_PCIE_FORM(socket, 2)                                                          \
  ADD_GOTO_PCIE_FORM(socket, 3)                                                          \
  oneof varid = NVIDIA_CONFIG_HII_CONTROL.UphySetting##socket[2],                        \
        questionid = KEY_UPHY2_SOCKET##socket##_CONFIG,                                  \
        prompt = STRING_TOKEN(STR_UPHY2_SOCKET##socket##_PROMPT),                        \
        help = STRING_TOKEN(STR_UPHY2_HELP),                                             \
        flags = INTERACTIVE | RESET_REQUIRED,                                            \
        suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.TH500Config == 1 AND                \
                   ideqval NVIDIA_CONFIG_HII_CONTROL.UphySetting##socket[2] > 2;         \
        option text = STRING_TOKEN(STR_DISABLED), value = 0, flags = 0;                  \
        option text = STRING_TOKEN(STR_PCIE_C4_X16), value = 1, flags = 0;               \
        option text = STRING_TOKEN(STR_PCIE_C4_X8_C5_X8), value = 2, flags = 0;          \
        endif;                                                                           \
        suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.TH500Config == 1 AND                \
                   ideqval NVIDIA_CONFIG_HII_CONTROL.UphySetting##socket[2] < 3;         \
        option text = STRING_TOKEN(STR_PCIE_C5_X4_NVLINK_X12), value = 3, flags = 0;     \
        option text = STRING_TOKEN(STR_PCIE_C5_X4_NVLINK_NO_PCIE), value = 4, flags = 0; \
        endif;                                                                           \
  endoneof;                                                                              \
  ADD_GOTO_PCIE_FORM(socket, 4)                                                          \
  ADD_GOTO_PCIE_FORM(socket, 5)                                                          \
  oneof varid = NVIDIA_CONFIG_HII_CONTROL.UphySetting##socket[3],                        \
        questionid = KEY_UPHY3_SOCKET##socket##_CONFIG,                                  \
        prompt = STRING_TOKEN(STR_UPHY3_SOCKET##socket##_PROMPT),                        \
        help = STRING_TOKEN(STR_UPHY3_HELP),                                             \
        flags = INTERACTIVE | RESET_REQUIRED,                                            \
        suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.TH500Config == 1 AND                \
                   ideqval NVIDIA_CONFIG_HII_CONTROL.UphySetting##socket[3] > 2;         \
        option text = STRING_TOKEN(STR_DISABLED), value = 0, flags = 0;                  \
        option text = STRING_TOKEN(STR_PCIE_C6_X16), value = 1, flags = 0;               \
        option text = STRING_TOKEN(STR_PCIE_C6_X8_C7_X8), value = 2, flags = 0;          \
        endif;                                                                           \
        suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.TH500Config == 1 AND                \
                   ideqval NVIDIA_CONFIG_HII_CONTROL.UphySetting##socket[3] < 3;         \
        option text = STRING_TOKEN(STR_PCIE_C7_X4_NVLINK_X12), value = 3, flags = 0;     \
        option text = STRING_TOKEN(STR_PCIE_C7_X4_NVLINK_NO_PCIE), value = 4, flags = 0; \
        endif;                                                                           \
  endoneof;                                                                              \
  ADD_GOTO_PCIE_FORM(socket, 6)                                                          \
  ADD_GOTO_PCIE_FORM(socket, 7)                                                          \
  oneof varid = NVIDIA_CONFIG_HII_CONTROL.UphySetting##socket[4],                        \
        questionid = KEY_UPHY4_SOCKET##socket##_CONFIG,                                  \
        prompt = STRING_TOKEN(STR_UPHY4_SOCKET##socket##_PROMPT),                        \
        help = STRING_TOKEN(STR_UPHY4_HELP),                                             \
        flags = INTERACTIVE | RESET_REQUIRED,                                            \
        option text = STRING_TOKEN(STR_DISABLED), value = 0, flags = 0;                  \
        option text = STRING_TOKEN(STR_PCIE_C8_X2), value = 1, flags = 0;                \
        option text = STRING_TOKEN(STR_PCIE_C8_X1_USB), value = 2, flags = 0;            \
  endoneof;                                                                              \
  ADD_GOTO_PCIE_FORM(socket, 8)                                                          \
  oneof varid = NVIDIA_CONFIG_HII_CONTROL.UphySetting##socket[5],                        \
        questionid = KEY_UPHY5_SOCKET##socket##_CONFIG,                                  \
        prompt = STRING_TOKEN(STR_UPHY5_SOCKET##socket##_PROMPT),                        \
        help = STRING_TOKEN(STR_UPHY5_HELP),                                             \
        flags = INTERACTIVE | RESET_REQUIRED,                                            \
        option text = STRING_TOKEN(STR_DISABLED), value = 0, flags = 0;                  \
        option text = STRING_TOKEN(STR_PCIE_C9_X2), value = 1, flags = 0;                \
  endoneof;                                                                              \
  ADD_GOTO_PCIE_FORM(socket, 9)                                                          \
  endif;                                                                                 \
  endform;

#define ADD_PCIE_FORM(socket, pcie)                                                               \
  form formid = TH500_SOCKET##socket##_PCIE##pcie##_CONFIGURATION_FORM_ID,                        \
       title = STRING_TOKEN(STR_PCIE##pcie##_CONFIG_FORM_TITLE);                                  \
  subtitle text = STRING_TOKEN(STR_NULL);                                                         \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.SocketEnabled[socket] == 0;                        \
  oneof varid = NVIDIA_CONFIG_HII_CONTROL.MaxSpeed##socket[pcie],                                 \
        questionid = KEY_SOCKET##socket##_PCIE##pcie##_MAX_SPEED,                                 \
        prompt = STRING_TOKEN(STR_PCIE_MAX_SPEED_SOCKET##socket##_PCIE##pcie##_TITLE),            \
        help = STRING_TOKEN(STR_PCIE_MAX_SPEED_HELP),                                             \
        flags = INTERACTIVE | RESET_REQUIRED,                                                     \
        option text = STRING_TOKEN(STR_PCIE_GEN5), value = 5, flags = 0;                          \
  option text = STRING_TOKEN(STR_PCIE_GEN4), value = 4, flags = 0;                                \
  option text = STRING_TOKEN(STR_PCIE_GEN3), value = 3, flags = 0;                                \
  option text = STRING_TOKEN(STR_PCIE_GEN2), value = 2, flags = 0;                                \
  option text = STRING_TOKEN(STR_PCIE_GEN1), value = 1, flags = 0;                                \
  endoneof;                                                                                       \
  oneof varid = NVIDIA_CONFIG_HII_CONTROL.MaxWidth##socket[pcie],                                 \
        questionid = KEY_SOCKET##socket##_PCIE##pcie##_MAX_WIDTH,                                 \
        prompt = STRING_TOKEN(STR_PCIE_MAX_WIDTH_SOCKET##socket##_PCIE##pcie##_TITLE),            \
        help = STRING_TOKEN(STR_PCIE_MAX_WIDTH_HELP),                                             \
        flags = INTERACTIVE | RESET_REQUIRED,                                                     \
        option text = STRING_TOKEN(STR_PCIE_X16), value = 16, flags = 0;                          \
  option text = STRING_TOKEN(STR_PCIE_X8), value = 8, flags = 0;                                  \
  option text = STRING_TOKEN(STR_PCIE_X4), value = 4, flags = 0;                                  \
  option text = STRING_TOKEN(STR_PCIE_X2), value = 2, flags = 0;                                  \
  option text = STRING_TOKEN(STR_PCIE_X1), value = 1, flags = 0;                                  \
  endoneof;                                                                                       \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.PCIeSlotNumConfigSupported == 0;                   \
  numeric varid = NVIDIA_CONFIG_HII_CONTROL.SlotNum##socket[pcie],                                \
          questionid = KEY_SOCKET##socket##_PCIE##pcie##_SLOT_NUM,                                \
          prompt = STRING_TOKEN(STR_PCIE_SLOT_NUM_SOCKET##socket##_PCIE##pcie##_TITLE),           \
          help = STRING_TOKEN(STR_PCIE_SLOT_NUM_HELP),                                            \
          flags = INTERACTIVE | RESET_REQUIRED | DISPLAY_UINT_HEX,                                \
          minimum = 0,                                                                            \
          maximum = 8191,                                                                         \
          step = 1,                                                                               \
          default = 0,                                                                            \
          endnumeric;                                                                             \
  endif;                                                                                          \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.AdvertiseAspmL1_##socket[pcie],                         \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_ADVERTISE_ASPML1,                          \
           prompt = STRING_TOKEN(STR_PCIE_ADVERTISE_ASPM_L1_SOCKET##socket##_PCIE##pcie##_TITLE),    \
           help = STRING_TOKEN(STR_NULL),                                                         \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.PCIeASPML1SSConfigSupported == 0;                  \
  grayoutif ideqval NVIDIA_CONFIG_HII_CONTROL.AdvertiseAspmL1_##socket[pcie] == 0;                   \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.AdvertiseAspmL1_1_##socket[pcie],                       \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_ADVERTISE_ASPML1_1,                        \
           prompt = STRING_TOKEN(STR_PCIE_ADVERTISE_ASPM_L1_1_SOCKET##socket##_PCIE##pcie##_TITLE),  \
           help = STRING_TOKEN(STR_NULL),                                                         \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.AdvertiseAspmL1_2_##socket[pcie],                       \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_ADVERTISE_ASPML1_2,                        \
           prompt = STRING_TOKEN(STR_PCIE_ADVERTISE_ASPM_L1_2_SOCKET##socket##_PCIE##pcie##_TITLE),  \
           help = STRING_TOKEN(STR_NULL),                                                         \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  endif;                                                                                          \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.AdvertisePciPmL1_2_##socket[pcie],                      \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_ADVERTISE_PCIPML1_2,                       \
           prompt = STRING_TOKEN(STR_PCIE_ADVERTISE_PCIPM_L1_2_SOCKET##socket##_PCIE##pcie##_TITLE), \
           help = STRING_TOKEN(STR_NULL),                                                         \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  endif;                                                                                          \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.SupportsClkReq##socket[pcie],                        \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_CLK_REQ,                                \
           prompt = STRING_TOKEN(STR_PCIE_SUPPORTS_CLK_REQ_SOCKET##socket##_PCIE##pcie##_TITLE),  \
           help = STRING_TOKEN(STR_PCIE_SUPPORTS_CLK_REQ_HELP),                                   \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.DisableDLFE##socket[pcie],                           \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_DISABLE_DLFE,                           \
           prompt = STRING_TOKEN(STR_PCIE_DISABLE_DLFE_SOCKET##socket##_PCIE##pcie##_TITLE),      \
           help = STRING_TOKEN(STR_PCIE_DISABLE_DLFE_HELP),                                       \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.EnableECRC_##socket[pcie],                           \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_ENABLE_ECRC,                            \
           prompt = STRING_TOKEN(STR_PCIE_ENABLE_ECRC_SOCKET##socket##_PCIE##pcie##_TITLE),       \
           help = STRING_TOKEN(STR_PCIE_ENABLE_ECRC_HELP),                                        \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.DisableOptionRom##socket[pcie],                      \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_DISABLE_OPT_ROM,                        \
           prompt = STRING_TOKEN(STR_PCIE_DISABLE_OPT_ROM_SOCKET##socket##_PCIE##pcie##_TITLE),   \
           help = STRING_TOKEN(STR_PCIE_DISABLE_OPT_ROM_HELP),                                    \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.DisableDPCAtRP_##socket[pcie],                       \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_DISABLE_DPC_AT_RP,                      \
           prompt = STRING_TOKEN(STR_PCIE_DISABLE_DPC_AT_RP_SOCKET##socket##_PCIE##pcie##_TITLE), \
           help = STRING_TOKEN(STR_PCIE_DISABLE_DPC_AT_RP_HELP),                                  \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.PCIeURCAConfigSupported == 0;                      \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.MaskUnsupportedRequest_##socket[pcie],               \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_MASK_UNSUPPORTED_REQUEST,               \
           prompt = STRING_TOKEN(STR_PCIE_MASK_UNSUPPORTED_REQUEST_SOCKET##socket##_PCIE##pcie##_TITLE), \
           help = STRING_TOKEN(STR_PCIE_MASK_UNSUPPORTED_REQUEST_HELP),                                  \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.MaskCompleterAbort_##socket[pcie],                   \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_MASK_COMPLETER_ABORT,                   \
           prompt = STRING_TOKEN(STR_PCIE_MASK_COMPLETER_ABORT_SOCKET##socket##_PCIE##pcie##_TITLE), \
           help = STRING_TOKEN(STR_PCIE_MASK_COMPLETER_ABORT_HELP),                                  \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.PCIePRSNTConfigSupported == 0;                     \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.SupportsPRSNT_##socket[pcie],                        \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_SUPPORTS_PRSNT,                         \
           prompt = STRING_TOKEN(STR_PCIE_SUPPORTS_PRSNT_SOCKET##socket##_PCIE##pcie##_TITLE),    \
           help = STRING_TOKEN(STR_PCIE_SUPPORTS_PRSNT_HELP),                                     \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  endif;                                                                                          \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.PCIeACSConfigSupported == 0;                       \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.AdvertiseACS_##socket[pcie],                         \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_ADVERTISE_ACS,                          \
           prompt = STRING_TOKEN(STR_PCIE_ADVERTISE_ACS_SOCKET##socket##_PCIE##pcie##_TITLE),     \
           help = STRING_TOKEN(STR_PCIE_ADVERTISE_ACS_HELP),                                      \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  endif;                                                                                          \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.PCIeOSNativeAERSupported == 0;                     \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.OsNativeAER_##socket[pcie],                          \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_OS_NATIVE_AER,                          \
           prompt = STRING_TOKEN(STR_PCIE_OS_NATIVE_AER_SOCKET##socket##_PCIE##pcie##_TITLE),     \
           help = STRING_TOKEN(STR_PCIE_OS_NATIVE_AER_HELP),                                      \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  endif;                                                                                          \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.PCIeOSNativePMESupported == 0;                     \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.OsNativePME_##socket[pcie],                          \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_OS_NATIVE_PME,                          \
           prompt = STRING_TOKEN(STR_PCIE_OS_NATIVE_PME_SOCKET##socket##_PCIE##pcie##_TITLE),     \
           help = STRING_TOKEN(STR_PCIE_OS_NATIVE_PME_HELP),                                      \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  endif;                                                                                          \
  suppressif ideqval NVIDIA_CONFIG_HII_CONTROL.PCIeDisableL23AtWarmResetSupported == 0;           \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.DisableL23AtWarmReset_##socket[pcie],                \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_DISABLE_L23_AT_WARM_RESET,              \
           prompt = STRING_TOKEN(STR_PCIE_DISABLE_L23_AT_WARM_RESET_SOCKET##socket##_PCIE##pcie##_TITLE), \
           help = STRING_TOKEN(STR_PCIE_DISABLE_L23_AT_WARM_RESET_HELP),                          \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  endif;                                                                                          \
  oneof varid = NVIDIA_CONFIG_HII_CONTROL.MaxPayloadSize##socket[pcie],                           \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_MAX_PAYLOAD_SIZE,                       \
           prompt = STRING_TOKEN(STR_PCIE_MAX_PAYLOAD_SIZE_SOCKET##socket##_PCIE##pcie##_TITLE),  \
           help = STRING_TOKEN(STR_PCIE_MAX_PAYLOAD_SIZE_HELP),                                   \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           option text = STRING_TOKEN(STR_AUTO), value = 0, flags = 0;                            \
           option text = STRING_TOKEN(STR_PCIE_128B), value = 1, flags = 0;                       \
           endoneof;                                                                              \
  checkbox varid = NVIDIA_CONFIG_HII_CONTROL.Extended10bitTagEnable##socket[pcie],                \
           questionid = KEY_SOCKET##socket##_PCIE##pcie##_EXTENDED_10BIT_TAG_ENABLE,              \
           prompt = STRING_TOKEN(STR_PCIE_EXTENDED_10BIT_TAG_ENABLE_SOCKET##socket##_PCIE##pcie##_TITLE), \
           help = STRING_TOKEN(STR_PCIE_EXTENDED_10BIT_TAG_ENABLE_HELP),                          \
           flags = INTERACTIVE | RESET_REQUIRED,                                                  \
           endcheckbox;                                                                           \
  numeric varid = NVIDIA_CONFIG_HII_CONTROL.DelayAfterPERST##socket[pcie],                        \
          questionid = KEY_SOCKET##socket##_PCIE##pcie##_DELAY_AFTER_PERST,                       \
          prompt = STRING_TOKEN(STR_PCIE_DELAY_AFTER_PERST_SOCKET##socket##_PCIE##pcie##_TITLE),  \
          help = STRING_TOKEN(STR_PCIE_DELAY_AFTER_PERST_HELP),                                   \
          flags = INTERACTIVE | RESET_REQUIRED | DISPLAY_UINT_DEC,                                \
          minimum = 0,                                                                            \
          maximum = 60,                                                                           \
          step = 1,                                                                               \
          default = 0,                                                                            \
          endnumeric;                                                                             \
  endif;                                                                                          \
  endif;                                                                                          \
  endform;

#define PCIE_SEG(socket, pcie)  (((socket) << 4) | ((pcie) & 0xF))

#endif // __NVIDIA_CONFIG_HII_H__
