#ifndef __NVIDIA_TEGRA_I2C_SLAVE_DEVICE_TREE_NODE_PROTOCOL_H__
#define __NVIDIA_TEGRA_I2C_SLAVE_DEVICE_TREE_NODE_PROTOCOL_H__

#include <Protocol/DeviceTreeNode.h>

typedef struct _NVIDIA_TEGRA_I2C_SLAVE_DEVICE_TREE_NODE_PROTOCOL NVIDIA_TEGRA_I2C_SLAVE_DEVICE_TREE_NODE_PROTOCOL;

typedef EFI_STATUS
	(*NVIDIA_TEGRA_I2C_SLAVE_DEVICE_TREE_NODE_PROTOCOL_LOOKUP_NODE)(
		IN CONST NVIDIA_TEGRA_I2C_SLAVE_DEVICE_TREE_NODE_PROTOCOL *This,
		IN CONST EFI_GUID                                         *DeviceGuid,
		IN UINT32                                                 DeviceIndex,
		OUT NVIDIA_DEVICE_TREE_NODE_PROTOCOL                      *DeviceTreeNode
	);

struct _NVIDIA_TEGRA_I2C_SLAVE_DEVICE_TREE_NODE_PROTOCOL {
    NVIDIA_TEGRA_I2C_SLAVE_DEVICE_TREE_NODE_PROTOCOL_LOOKUP_NODE    LookupNode;
};

extern EFI_GUID  gNVIDIAI2cSlaveDeviceTreeNodeProtocolGuid;
#endif//__NVIDIA_TEGRA_I2C_SLAVE_DEVICE_TREE_NODE_PROTOCOL_H__
